In [155]:
import numpy as np
import pandas as pd

### 7.1 Eksik Verilerle Başa Çıkma

In [156]:
float_data = pd.Series([1.2, -3.5, np.nan, 0])
float_data

0    1.2
1   -3.5
2    NaN
3    0.0
dtype: float64

In [157]:
float_data.isna()

0    False
1    False
2     True
3    False
dtype: bool

In [158]:
pd.isna(float_data)

0    False
1    False
2     True
3    False
dtype: bool

In [159]:
string_data = pd.Series(["aardvark", np.nan, None, "avocado"])
string_data

0    aardvark
1         NaN
2        None
3     avocado
dtype: object

In [160]:
string_data.isna()

0    False
1     True
2     True
3    False
dtype: bool

In [161]:
float_data = pd.Series([1, 2, None], dtype='float64')

In [162]:
float_data

0    1.0
1    2.0
2    NaN
dtype: float64

In [163]:
float_data.isna()

0    False
1    False
2     True
dtype: bool

### Eksik Verileri Filtreleme

In [164]:
data = pd.Series([1, np.nan, 3.5, np.nan, 7])
data.dropna()

0    1.0
2    3.5
4    7.0
dtype: float64

In [165]:
data[data.notna()]

0    1.0
2    3.5
4    7.0
dtype: float64

In [166]:
data = pd.DataFrame([[1., 6.5, 3.], [1., np.nan, np.nan],
                     [np.nan, np.nan, np.nan], [np.nan, 6.5, 3.]])

In [167]:
data

     0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [168]:
data.dropna()

     0    1    2
0  1.0  6.5  3.0

In [169]:
data.dropna(how="all")

     0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
3  NaN  6.5  3.0

In [170]:
data.dropna(how="any")

     0    1    2
0  1.0  6.5  3.0

In [171]:
data[4] = np.nan
data

     0    1    2   4
0  1.0  6.5  3.0 NaN
1  1.0  NaN  NaN NaN
2  NaN  NaN  NaN NaN
3  NaN  6.5  3.0 NaN

In [172]:
data.dropna(axis="columns", how="all")

     0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [173]:
data.dropna(axis="columns", how="any")

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3]

In [174]:
df = pd.DataFrame(np.random.standard_normal((7,3)))

In [175]:
df

          0         1         2
0  1.007189 -1.296221  0.274992
1  0.228913  1.352917  0.886429
2 -2.001637 -0.371843  1.669025
3 -0.438570 -0.539741  0.476985
4  3.248944 -1.021228 -0.577087
5  0.124121  0.302614  0.523772
6  0.000940  1.343810 -0.713544

In [176]:
df.iloc[:4, 1] = np.nan

In [177]:
df.iloc[:2, 2]= np.nan

In [178]:
df

          0         1         2
0  1.007189       NaN       NaN
1  0.228913       NaN       NaN
2 -2.001637       NaN  1.669025
3 -0.438570       NaN  0.476985
4  3.248944 -1.021228 -0.577087
5  0.124121  0.302614  0.523772
6  0.000940  1.343810 -0.713544

In [179]:
df.dropna()

          0         1         2
4  3.248944 -1.021228 -0.577087
5  0.124121  0.302614  0.523772
6  0.000940  1.343810 -0.713544

In [180]:
df.dropna(how="all")

          0         1         2
0  1.007189       NaN       NaN
1  0.228913       NaN       NaN
2 -2.001637       NaN  1.669025
3 -0.438570       NaN  0.476985
4  3.248944 -1.021228 -0.577087
5  0.124121  0.302614  0.523772
6  0.000940  1.343810 -0.713544

In [181]:
df.dropna(thresh=2)

          0         1         2
2 -2.001637       NaN  1.669025
3 -0.438570       NaN  0.476985
4  3.248944 -1.021228 -0.577087
5  0.124121  0.302614  0.523772
6  0.000940  1.343810 -0.713544

In [182]:
df.dropna(thresh=1)

          0         1         2
0  1.007189       NaN       NaN
1  0.228913       NaN       NaN
2 -2.001637       NaN  1.669025
3 -0.438570       NaN  0.476985
4  3.248944 -1.021228 -0.577087
5  0.124121  0.302614  0.523772
6  0.000940  1.343810 -0.713544

### Eksik Verileri Doldurma

In [183]:
df.fillna(0)

          0         1         2
0  1.007189  0.000000  0.000000
1  0.228913  0.000000  0.000000
2 -2.001637  0.000000  1.669025
3 -0.438570  0.000000  0.476985
4  3.248944 -1.021228 -0.577087
5  0.124121  0.302614  0.523772
6  0.000940  1.343810 -0.713544

In [184]:
df.fillna({1: 0.5, 2: 0})

          0         1         2
0  1.007189  0.500000  0.000000
1  0.228913  0.500000  0.000000
2 -2.001637  0.500000  1.669025
3 -0.438570  0.500000  0.476985
4  3.248944 -1.021228 -0.577087
5  0.124121  0.302614  0.523772
6  0.000940  1.343810 -0.713544

In [185]:
df = pd.DataFrame(np.random.standard_normal((6,3)))
df.iloc[2:, 1] = np.nan
df.iloc[4:, 2] = np.nan

In [186]:
df

          0         1         2
0 -0.831154 -2.370232 -1.860761
1 -0.860757  0.560145 -1.265934
2  0.119827       NaN  0.332883
3 -2.359419       NaN -1.541996
4 -0.970736       NaN       NaN
5  0.377984       NaN       NaN

In [187]:
df.fillna(method="ffill")

C:\Users\safye\AppData\Local\Temp\ipykernel_25508\3944122520.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method="ffill")

          0         1         2
0 -0.831154 -2.370232 -1.860761
1 -0.860757  0.560145 -1.265934
2  0.119827  0.560145  0.332883
3 -2.359419  0.560145 -1.541996
4 -0.970736  0.560145 -1.541996
5  0.377984  0.560145 -1.541996

In [188]:
data = pd.Series([1., np.nan, 3.5, np.nan, 7])
data

0    1.0
1    NaN
2    3.5
3    NaN
4    7.0
dtype: float64

In [189]:
data.fillna(data.mean())

0    1.000000
1    3.833333
2    3.500000
3    3.833333
4    7.000000
dtype: float64

### 7.2 Veri Dönüştürme

In [190]:
data = pd.DataFrame({"k1": ["one", "two"] * 3 + ["two"],
                     "k2": [1, 1, 2, 3, 3, 4, 4]})

In [191]:
data

    k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4
6  two   4

In [192]:
data.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6     True
dtype: bool

In [193]:
data.drop_duplicates()

    k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4

In [194]:
data["v1"] = range(7)
data

    k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
5  two   4   5
6  two   4   6

In [195]:
data.drop_duplicates(subset=["k1"])

    k1  k2  v1
0  one   1   0
1  two   1   1

### Bir Fonksiyon veya Eşleme Kullanarak Veri Dönüştürme

In [196]:
data = pd.DataFrame({"food": ["bacon", "pulled pork", "bacon",
                              "pastrami", "corned beef", "bacon",
                              "pastrami", "honey ham", "nova lox"],
                              "ounces": [4, 3, 12, 6, 7.5, 8, 3, 5, 6]})

In [197]:
data

          food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3     pastrami     6.0
4  corned beef     7.5
5        bacon     8.0
6     pastrami     3.0
7    honey ham     5.0
8     nova lox     6.0

In [198]:
meat_to_animal = {
 "bacon": "pig",
 "pulled pork": "pig",
 "pastrami": "cow",
 "corned beef": "cow",
 "honey ham": "pig",
 "nova lox": "salmon"
}

In [199]:
data["animal"] = data["food"].map(meat_to_animal)
data

          food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     pastrami     6.0     cow
4  corned beef     7.5     cow
5        bacon     8.0     pig
6     pastrami     3.0     cow
7    honey ham     5.0     pig
8     nova lox     6.0  salmon

In [200]:
def get_animal(x):
    return meat_to_animal[x]

In [201]:
data["food"].map(get_animal)

0       pig
1       pig
2       pig
3       cow
4       cow
5       pig
6       cow
7       pig
8    salmon
Name: food, dtype: object

In [202]:
data = pd.Series([1., -999., 2., -999., -1000., 3.])

In [203]:
data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [204]:
data.replace(-999, np.nan)

0       1.0
1       NaN
2       2.0
3       NaN
4   -1000.0
5       3.0
dtype: float64

In [205]:
data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [206]:
data.replace([-999, -1000], np.nan)

0    1.0
1    NaN
2    2.0
3    NaN
4    NaN
5    3.0
dtype: float64

In [207]:
data.replace([-999, -1000], [np.nan, 0])

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [208]:
data.replace({-999: np.nan, -1000: 0})

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

### Eksen İndekslerini Yeniden Adlandırma

In [209]:
data = pd.DataFrame(np.arange(12).reshape((3, 4)),
                    index=["Ohio", "Colorado", "New York"],
                    columns=["one", "two", "three", "four"])

In [210]:
def transform(x):
    return x[:4].upper()

In [211]:
data.index.map(transform)

Index(['OHIO', 'COLO', 'NEW '], dtype='object')

In [212]:
data.index = data.index.map(transform)

In [213]:
data

      one  two  three  four
OHIO    0    1      2     3
COLO    4    5      6     7
NEW     8    9     10    11

### Ayrıklaştırma ve Gruplandırma (Binning)

In [214]:
ages = [20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32]

In [215]:
bins = [18, 25, 35, 60, 100]
age_categories = pd.cut(ages, bins)

In [216]:
age_categories

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64, right]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [217]:
age_categories.codes

array([0, 0, 0, 1, 0, 0, 2, 1, 3, 2, 2, 1], dtype=int8)

In [218]:
age_categories.categories

IntervalIndex([(18, 25], (25, 35], (35, 60], (60, 100]], dtype='interval[int64, right]')

In [219]:
age_categories.categories[0]

Interval(18, 25, closed='right')

In [220]:
pd.value_counts(age_categories)

C:\Users\safye\AppData\Local\Temp\ipykernel_25508\3010498523.py:1: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  pd.value_counts(age_categories)

(18, 25]     5
(25, 35]     3
(35, 60]     3
(60, 100]    1
Name: count, dtype: int64

In [221]:
pd.cut(ages, bins, right=False)

[[18, 25), [18, 25), [25, 35), [25, 35), [18, 25), ..., [25, 35), [60, 100), [35, 60), [35, 60), [25, 35)]
Length: 12
Categories (4, interval[int64, left]): [[18, 25) < [25, 35) < [35, 60) < [60, 100)]

In [222]:
group_names = ["yputh", "YoungAdult", "MiddleAged", "Senior"]

In [223]:
pd.cut(ages, bins, labels=group_names)

['yputh', 'yputh', 'yputh', 'YoungAdult', 'yputh', ..., 'YoungAdult', 'Senior', 'MiddleAged', 'MiddleAged', 'YoungAdult']
Length: 12
Categories (4, object): ['yputh' < 'YoungAdult' < 'MiddleAged' < 'Senior']

In [224]:
data = np.random.uniform(size=20)
data

array([0.97322998, 0.63405438, 0.88842172, 0.49541476, 0.35161653,
       0.71423037, 0.50392912, 0.22563761, 0.24497444, 0.7928007 ,
       0.49517241, 0.91509367, 0.94537183, 0.53323223, 0.25249259,
       0.72086206, 0.36743876, 0.49864844, 0.22657505, 0.35356565])

In [225]:
pd.cut(data, 4, precision=2)

[(0.79, 0.97], (0.6, 0.79], (0.79, 0.97], (0.41, 0.6], (0.22, 0.41], ..., (0.6, 0.79], (0.22, 0.41], (0.41, 0.6], (0.22, 0.41], (0.22, 0.41]]
Length: 20
Categories (4, interval[float64, right]): [(0.22, 0.41] < (0.41, 0.6] < (0.6, 0.79] < (0.79, 0.97]]

In [226]:
pd.value_counts(pd.cut(data, 4, precision=2))

C:\Users\safye\AppData\Local\Temp\ipykernel_25508\3248861558.py:1: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  pd.value_counts(pd.cut(data, 4, precision=2))

(0.22, 0.41]    7
(0.41, 0.6]     5
(0.79, 0.97]    5
(0.6, 0.79]     3
Name: count, dtype: int64

In [227]:
data = np.random.standard_normal(1000)
data

array([ 1.34974221e+00, -1.33260971e+00,  1.07462269e+00,  7.23641505e-01,
        6.90001853e-01,  1.00154344e+00, -5.03087391e-01, -6.22274225e-01,
       -9.21168608e-01, -7.26213493e-01,  2.22895546e-01,  5.13161009e-02,
       -1.15771947e+00,  8.16706936e-01,  4.33609606e-01,  1.01073695e+00,
        1.82487521e+00, -9.97518248e-01,  8.50591099e-01, -1.31577601e-01,
        9.12414152e-01,  1.88210680e-01,  2.16946144e+00, -1.14928205e-01,
        2.00369736e+00,  2.96101523e-02,  7.95253156e-01,  1.18109754e-01,
       -7.48531548e-01,  5.84969738e-01,  1.52676573e-01, -1.56565729e+00,
       -5.62540188e-01, -3.26641392e-02, -9.29006202e-01, -4.82572646e-01,
       -3.62638461e-02,  1.09539006e+00,  9.80928477e-01, -5.89487686e-01,
        1.58170009e+00, -5.28734826e-01,  4.57001871e-01,  9.29968759e-01,
       -1.56927061e+00, -1.02248698e+00, -4.02826924e-01,  2.20486863e-01,
       -1.93401108e-01,  6.69158336e-01, -1.64898482e+00, -2.25279725e+00,
       -1.16683222e+00,  3.53607102e-01,  7.02110171e-01, -2.74569205e-01,
       -1.39142188e-01,  1.07657222e-01, -6.06545125e-01, -4.17064408e-01,
       -1.70070368e-02, -1.22414528e+00, -1.80083991e+00,  1.63473620e+00,
        9.89008302e-01,  4.57940143e-01,  5.55154410e-01,  1.30671972e+00,
       -4.40553570e-01, -3.01350280e-01,  4.98791490e-01, -8.23991040e-01,
        1.32056584e+00,  5.07964786e-01, -6.53437675e-01,  1.86979514e-01,
       -3.91725249e-01, -2.72292975e-01, -1.71414356e-02,  6.80320749e-01,
        6.35512357e-01, -7.57176502e-01,  7.18085834e-01, -3.04273076e-01,
       -1.67779025e+00,  4.26986085e-01, -1.56373985e+00, -3.67487521e-01,
        1.04591253e+00,  1.21995436e+00, -2.47699116e-01, -4.16232132e-01,
       -1.16747004e-01, -1.84478762e+00,  2.06870785e+00, -7.76967474e-01,
        1.44016687e+00, -1.10557360e-01,  1.22738699e+00,  1.92078426e+00,
        7.46433038e-01,  2.22465959e+00, -6.79400410e-01,  7.27368782e-01,
       -8.68730734e-01, -1.21385091e+00, -4.70630931e-01, -9.19241697e-01,
       -8.38826689e-01,  4.35155305e-01, -5.57804717e-01, -5.67454871e-01,
       -3.72641553e-01, -9.26556901e-01,  1.75510839e+00,  1.20980999e+00,
        1.27002473e+00, -9.74378127e-01, -6.34709255e-01, -3.95700752e-01,
       -2.89435900e-01, -7.34297072e-01, -7.28504679e-01,  8.38775073e-01,
        2.66893213e-01,  7.21194339e-01,  9.10982642e-01, -1.02090261e+00,
       -1.41341604e+00,  1.29660784e+00,  2.52275209e-01,  1.12748110e+00,
       -5.68363447e-01,  3.09362168e-01, -5.77385473e-01, -1.16863407e+00,
       -8.25019972e-01, -2.64440949e+00, -1.52985803e-01, -7.51921003e-01,
       -1.32609252e-01,  1.45729970e+00,  6.09511845e-01, -4.93779257e-01,
        1.23997988e+00, -1.35722140e-01,  1.43004181e+00, -8.46852451e-01,
        6.03282130e-01,  1.26357226e+00, -2.55490556e-01, -4.45688380e-01,
        4.68366681e-01, -9.61603924e-01, -1.82450454e+00,  6.25428156e-01,
        1.02287238e+00,  1.10742460e+00,  9.09370895e-02, -3.50108657e-01,
        2.17957016e-01, -8.94813130e-01, -1.74149395e+00, -1.05225574e+00,
        1.43660279e+00, -5.76207386e-01, -2.42029443e+00, -1.06232963e+00,
        2.37372262e-01,  9.57369064e-04,  6.52531808e-02, -1.36752411e+00,
       -3.02800519e-02,  9.40489321e-01, -6.42436751e-01,  1.04017925e+00,
       -1.08292226e+00,  4.29213588e-01, -2.36223669e-01,  6.41817816e-01,
       -3.31660557e-01,  1.39407223e+00, -1.07674194e+00, -1.92465982e-01,
       -8.71187651e-01,  4.20851997e-01, -1.21141107e+00, -2.58866912e-01,
       -5.81646850e-01, -1.26042063e+00,  4.64574793e-01, -1.07024091e+00,
        8.04222698e-01, -1.56735508e-01,  2.01039001e+00, -8.87104430e-01,
       -9.77936232e-01, -2.67217350e-01,  4.83337822e-01, -4.00332733e-01,
        4.49880415e-01,  3.99593953e-01, -1.51574804e-01, -2.55793406e+00,
        1.60806841e-01,  7.65250677e-02, -2.97204166e-01, -1.29427402e+00,
       -8.85180013e-01, -1.87496526e-01, -4.93560000e-01, -1.15412964e-01,
       -3.50744607e-01,  4.46973764e-02, -8.97756316e-01,  8.90873502e-01,
       -1.15118516e+00, -2.61230270e+00,  1.14125019e+00, -8.67135525e-01,
        3.83583258e-01, -4.37030164e-01,  3.47488810e-01, -1.23017904e+00,
        5.71078139e-01,  6.00612128e-02, -2.25523994e-01,  1.34972614e+00,
        1.35029973e+00, -3.86653322e-01,  8.65989542e-01,  1.74723360e+00,
       -1.41024614e+00, -3.78241525e-01, -3.45820667e-01,  3.80062465e-01,
        1.88994673e-01,  1.32329820e+00, -2.26458859e+00, -9.14978611e-01,
       -4.78964164e-01,  1.04718450e+00,  9.23948418e-01, -1.14150141e-01,
        4.05802443e-01,  2.88451808e-01, -4.34788492e-01,  3.58755633e-01,
       -3.88244944e-01,  2.12874629e+00,  1.40960468e+00, -1.05434278e-01,
        7.00428367e-01,  2.09285188e+00, -1.36971796e-01, -9.30489423e-01,
        3.27497234e-01,  1.30301308e+00, -1.40940236e+00, -1.44125945e-01,
       -7.16414024e-01,  1.03614186e-01, -1.49571856e+00, -1.17489356e+00,
        2.61399909e+00, -6.89307399e-01, -7.51652636e-01,  6.36280961e-01,
       -1.15764416e+00,  6.14679924e-01,  1.02139111e+00,  6.68272492e-01,
       -8.09535482e-01, -9.08124573e-01,  1.51228939e+00,  9.51174320e-02,
        1.18466855e+00,  6.37032934e-01, -5.39274587e-01, -5.51009929e-02,
       -1.13592579e+00, -1.70506254e-01, -1.15808727e+00,  1.10459914e+00,
        6.34238100e-01,  1.25968335e+00,  9.64930776e-01, -4.34445938e-01,
       -8.79602860e-01, -6.94838230e-01,  1.22637405e+00,  4.57278649e-01,
        1.15698625e-01,  1.01404235e+00, -1.13500772e+00, -2.63370582e-01,
        1.30642518e+00, -1.61084101e+00, -1.02662069e+00,  1.24157279e+00,
       -1.56759532e-01, -2.44909553e+00, -1.03394802e+00,  1.59953363e+00,
        4.74070770e-01,  1.51325927e-01, -5.42173166e-01, -4.75496217e-01,
        1.06402612e-01, -1.30822819e+00,  2.17318475e+00,  5.64561217e-01,
       -1.90480765e-01, -9.16934390e-01, -9.75813606e-01,  2.21230269e+00,
        7.39306826e-02,  1.81859456e+00, -1.58153100e+00, -7.74363409e-01,
        5.52936493e-01,  1.06061390e-01,  3.92752804e+00, -2.55125599e-01,
        8.54137315e-01, -3.64806532e-01,  1.31101737e-01, -6.97613896e-01,
        1.33564946e+00, -1.51038858e-01,  4.42937851e-01,  9.41571221e-01,
        5.33363953e-01,  3.56266193e-01, -1.01153190e-02,  1.41575317e+00,
        5.66105533e-01,  4.56487352e-01,  1.94788105e-01, -6.55053757e-01,
       -5.65230094e-01,  3.17687312e+00,  9.59532542e-01, -9.75339835e-01,
       -1.11674210e+00, -1.10437634e+00, -8.98755175e-01, -1.36663236e+00,
        4.51401732e-01, -1.58722181e+00, -7.32788830e-01, -5.14562627e-01,
       -6.11876053e-01, -3.15986670e-02,  2.34127888e-01,  2.71936281e-01,
        1.23076935e+00,  1.28830616e+00,  8.51813508e-01, -1.52918061e+00,
       -1.55171499e+00,  2.97292917e-01,  3.44791201e-01, -3.98103360e-01,
        4.29404057e-01, -2.85944649e-01, -2.22843700e+00,  6.65587850e-02,
        4.89964761e-01,  1.86792585e+00,  2.07043780e+00, -2.45383227e-01,
        7.62302108e-01,  1.29015475e-01,  6.27075914e-01, -1.06223474e+00,
       -1.49950345e+00,  5.45154193e-01,  4.00823267e-01, -1.94623039e+00,
        5.05031784e-01, -9.10489138e-01, -2.19696285e-01,  4.08055383e-01,
       -6.03145411e-01, -3.61132594e-01,  5.64024524e-01, -1.05661656e+00,
        1.39195005e+00, -1.76126767e+00, -9.11633128e-01,  6.58339264e-01,
       -1.57946584e+00,  4.57705976e-01, -1.83268092e-01, -6.85483896e-01,
        1.06431315e-01, -3.18236084e-01,  4.33712973e-01,  5.71825929e-01,
        5.67106029e-01,  8.15769654e-02, -3.02334871e-01, -7.26916388e-01,
        1.80335113e-01, -5.20208734e-01,  3.98092081e-01, -9.16935074e-01,
       -8.26501345e-02, -1.93969081e+00,  1.40799436e+00,  1.51240649e+00,
        5.26493120e-01, -2.66930833e-01,  8.62284048e-01,  8.38030660e-02,
       -1.87233890e+00, -9.62791017e-01,  8.00668292e-02,  1.28726442e-01,
       -4.79120340e-01, -6.40280504e-01,  7.45973801e-01, -6.22547063e-01,
        9.36289315e-01,  7.50018377e-01, -5.67150282e-02,  2.30067451e+00,
        5.69497467e-01,  1.48940968e+00,  1.26425028e+00, -7.61837213e-01,
       -3.31616898e-01, -1.75131543e+00,  6.28894111e-01,  2.82501864e-01,
       -1.33813943e+00, -5.00606850e-01,  1.21645030e-01,  1.70832347e+00,
       -9.70999448e-01, -6.19332343e-01, -7.26708132e-01,  1.22165542e+00,
        5.03699288e-01, -1.38787408e+00,  2.04851420e-01,  6.03705216e-01,
        5.45680309e-01,  2.35477019e-01,  1.11834994e-01, -1.25150375e+00,
       -2.94934350e+00,  6.34634161e-01,  1.24157016e-01,  1.29762249e+00,
       -1.68693341e+00,  1.08953905e+00,  2.06088174e+00, -2.41235326e-01,
       -9.47872180e-01,  6.76294029e-01, -6.53356162e-01, -6.52295298e-01,
        5.28827604e-01,  3.57793249e-01,  1.88649360e-01,  8.69416879e-01,
       -5.06674481e-02, -7.16364575e-01, -1.03258721e-01, -1.14103658e+00,
       -5.00776901e-01, -3.89301370e-01, -4.73850530e-01,  1.28664304e-01,
        1.53694305e-01,  4.44790058e-01,  1.28531667e-01,  2.52529866e-01,
       -9.40638663e-01,  1.00214545e+00, -5.25414984e-01, -8.87400936e-01,
        1.83131360e+00, -9.23029332e-01,  7.00537687e-01, -8.92151198e-01,
        2.30074000e+00, -8.17765299e-01,  5.13759632e-01,  6.23586943e-01,
        1.48920593e+00,  1.94047867e+00,  5.43237129e-01,  5.06190912e-01,
        1.66201449e+00, -1.18920250e+00,  9.35974490e-02, -5.39163905e-01,
       -1.43739560e+00,  1.87937386e-01, -4.50454457e-01, -5.16878232e-01,
       -9.56356677e-02,  3.16423805e-01,  6.03334657e-01, -1.49459146e+00,
       -1.10894079e-01,  2.41289404e-01, -5.82645109e-01, -2.41112652e-01,
        2.36360537e-01,  1.24720725e-01,  1.04632598e+00, -2.73091856e-01,
       -5.34834020e-01, -3.06563305e-01, -1.62242665e-01, -1.08323220e+00,
        7.08401493e-01,  1.52074304e+00,  2.90343183e-01, -6.83066330e-01,
       -9.50312866e-01,  4.00709936e-01, -1.26071684e-01,  3.98204888e-01,
        1.41638473e-01, -2.64141422e-01, -4.52212074e-01,  7.58201973e-01,
       -5.15583498e-01, -5.91202322e-01,  8.96745784e-01, -9.71437524e-01,
        1.84080991e+00,  1.53881232e-01, -2.74083943e-01, -1.78492569e+00,
        9.81006686e-01, -8.73717140e-01, -1.01563442e+00, -4.11243537e-01,
        1.46562117e+00, -1.00621906e+00, -9.02147762e-01,  7.52769143e-01,
       -4.90508527e-01, -5.24672210e-01, -6.99195861e-01,  3.52360939e-01,
        6.81025983e-02, -9.30341707e-01,  8.45399560e-01,  1.64723816e-02,
        8.44962955e-01,  1.85083395e+00,  2.20742409e-02, -1.36917902e+00,
        8.87203523e-01,  1.43311821e-02, -7.41547051e-02, -4.85647878e-02,
        1.23502145e+00, -4.33294924e-01,  1.39103546e+00,  8.20210741e-01,
       -2.47423465e-01,  3.02270746e-01,  5.43980361e-01, -9.42368504e-01,
       -1.26638281e+00,  9.37249545e-01, -7.20102245e-01, -1.59395154e+00,
       -3.75497816e-01, -9.58703834e-01,  7.94336400e-01, -1.60510784e+00,
        5.43710253e-01,  9.25166364e-01, -1.46962860e+00, -3.99592346e-01,
        1.41734264e+00, -8.97608668e-01,  1.84480502e+00,  1.25316821e+00,
       -1.49093242e+00, -2.77339246e-02,  1.37523596e+00, -2.52081701e-02,
       -6.67880179e-01, -2.86801753e+00,  2.10688543e-01,  1.28715531e+00,
       -5.74305988e-01,  4.95326647e-01,  3.96049590e-01,  5.88798190e-01,
       -1.28175713e+00,  2.02992261e+00, -5.01944516e-01, -1.59284566e-01,
       -1.49621630e+00,  1.14477139e-02,  4.19445985e-01,  2.05121388e+00,
       -3.68765333e-01, -1.68925468e+00,  1.47681161e-01, -1.80998392e-01,
        1.58059054e-01, -3.96615422e-01, -4.00236630e-01, -8.24895666e-01,
       -2.44440446e-01,  1.21945743e+00, -4.33630492e-01,  8.61183873e-01,
       -3.34503693e-01,  1.59559959e-01, -9.84164476e-01,  7.54084974e-01,
       -2.84391662e-01,  3.24797530e-01, -8.85424602e-01, -1.28089348e+00,
        1.96109935e-01,  9.54644156e-01, -8.00971332e-01,  1.58514730e-02,
        1.08755329e+00, -6.31242820e-01, -2.26893249e-02,  6.85879242e-01,
        5.19179208e-01,  1.82701892e-01,  2.04647381e-01, -2.65986356e-01,
       -2.27288704e-04,  1.23945232e+00, -8.19715256e-01, -2.60388907e-01,
        5.19140257e-01,  1.43091645e-01, -1.16677747e-01,  1.49674411e+00,
       -1.48427438e+00, -1.67118276e+00,  9.17173409e-01, -7.58014151e-01,
        2.06479240e+00, -8.50778396e-01,  4.99450713e-01, -7.92663655e-02,
       -1.40329264e+00,  1.57894791e+00,  3.69028988e-04,  9.00884914e-01,
       -4.54869220e-01, -8.64546645e-01,  1.12911990e+00,  5.78744129e-02,
       -4.33738666e-01,  9.26976374e-02, -1.39782015e+00,  1.45782265e+00,
       -1.76756916e-01, -2.54240300e-01, -1.26343750e+00,  4.52262741e-01,
       -8.40117409e-01, -5.02678071e-01,  5.13392587e-01,  1.64165300e+00,
        5.80790036e-01, -1.70734027e+00, -1.78355431e-01, -8.28459954e-01,
        1.28631168e+00, -4.06452362e-01,  1.56632047e-01,  5.21066804e-02,
        9.55813177e-01,  7.43191501e-01, -4.86323084e-01,  1.92046727e+00,
       -6.52749023e-01, -1.73303777e-01, -3.60410082e-01, -3.80413977e-01,
       -1.29813981e+00,  5.27919008e-01, -9.31002763e-02,  4.01184681e-01,
       -1.02583380e-01,  3.08690977e-02,  2.61610051e+00, -7.85577945e-01,
       -5.06998121e-01, -2.01820572e+00, -6.76853138e-01,  2.66674368e+00,
        1.45145615e+00,  6.34628855e-01, -5.02826864e-01,  5.12931659e-01,
        1.75677937e+00, -9.74310801e-01,  6.80397048e-01,  9.55798726e-01,
        1.50153548e+00, -7.56265648e-01,  4.73504604e-01,  1.71374345e+00,
       -1.14769922e+00,  2.90322050e-03, -1.10057036e+00, -2.97531782e-01,
        5.02409078e-01, -9.87418981e-04, -6.74560278e-01,  2.97958279e-01,
        1.46557314e+00, -3.03628594e-01, -9.94479885e-01,  1.89889991e-01,
       -1.68402957e+00, -4.58380742e-01,  5.43405908e-01, -1.18726426e+00,
       -4.12641693e-01,  1.17712535e+00, -3.13704165e-01,  1.57903162e+00,
        3.75388236e-01, -1.56813882e+00, -9.00886519e-01,  6.52345519e-01,
        8.71600314e-01,  2.68216170e-01,  9.47681220e-01,  1.47267588e-01,
       -1.77245546e+00,  5.92419611e-01,  9.03254745e-02,  6.51121454e-01,
       -8.11946962e-02,  8.01897603e-01,  1.39845227e-01, -5.01002762e-01,
       -1.28302559e-01,  4.14605966e-01,  6.04577786e-01,  2.13409475e+00,
        9.41187837e-01, -9.31456796e-01, -1.24667539e-01,  2.00696291e-01,
        1.80256286e-01, -3.20370097e-01, -1.59612803e+00, -1.28169898e+00,
        1.50258575e+00,  6.53538002e-01, -3.19536626e-01,  9.55094011e-01,
        2.61995955e-01,  1.60792901e-01, -5.71680642e-01,  3.51660059e-01,
        1.11498006e+00,  1.18326826e+00,  1.06094106e+00,  5.10712630e-01,
       -9.38783998e-01, -5.46496141e-01,  5.90029971e-01,  1.48218524e+00,
        1.02118104e-01,  2.65438049e-01,  3.19307433e-03, -2.59501150e+00,
       -1.55556933e+00,  1.10299596e+00,  5.54736504e-01, -1.28901164e+00,
        3.85241648e-01, -1.71729173e+00, -1.01835313e+00,  5.16353173e-02,
        5.03298710e-01, -5.43186231e-01, -5.06678417e-01,  7.29652833e-01,
        4.34273363e-01, -1.13367361e+00,  1.42395334e+00,  2.66351537e-01,
       -8.54264393e-01, -5.50596561e-01, -6.19109859e-01,  1.03893339e+00,
       -9.10610825e-01,  5.29952567e-01, -8.47143615e-03, -1.12903825e+00,
        5.69854191e-01, -8.63391622e-01, -1.35614427e+00, -5.71515569e-02,
       -1.08621122e-01,  1.65238409e+00, -1.35092808e+00, -5.46096737e-01,
        9.91400184e-01,  2.20099739e+00,  4.27899791e-01,  2.90468283e-01,
        6.11953096e-01, -5.12450984e-01, -7.24230691e-01,  1.69288190e+00,
       -2.99339120e-01,  1.57172719e+00,  4.61444067e-01, -6.73829701e-01,
       -1.14103626e+00, -1.22891798e+00, -1.15928246e+00, -3.20829018e-01,
        1.08834758e+00, -9.06203145e-01, -4.64152062e-01, -5.13378373e-01,
        1.61783768e+00, -8.16650606e-01,  2.44719605e-01, -1.31109423e+00,
        3.88406495e-01,  1.59237371e+00,  8.70399037e-01,  3.35249325e-01,
        6.48959907e-01, -1.83151791e-01,  5.00241270e-01,  1.36882639e+00,
        8.95091842e-01,  6.47293372e-01, -5.67878708e-01, -5.79517447e-01,
       -7.51448573e-01,  1.07551918e+00, -6.21142360e-01,  1.87855572e+00,
        1.26023993e+00,  3.10050973e-01,  1.06402292e-01,  2.48012997e-01,
       -1.39383959e+00, -6.69436307e-01, -5.66791474e-01, -3.81778903e-01,
       -9.46546907e-01, -1.06510300e+00, -1.33182618e+00, -9.86453191e-01,
       -3.78391147e-01,  7.64711975e-01,  6.03594165e-02,  6.18509999e-01,
       -4.84921020e-01, -2.80530240e-01,  4.06962904e-01,  1.02518779e+00,
        2.54751681e-01,  8.75239905e-02,  7.06983543e-02, -5.73152603e-01,
        1.22892597e+00, -9.62201893e-01,  1.52555676e+00,  8.27282589e-01,
        9.12470470e-01, -1.27292343e-01,  6.34316641e-01, -1.53089843e+00,
       -1.29070149e+00, -5.26228341e-01, -1.13223396e+00, -4.99797127e-01,
       -7.28463087e-01, -5.83144170e-01,  3.29290657e-01, -8.26860798e-01,
       -5.36867983e-01, -5.62980134e-01,  9.18404800e-01, -7.93993782e-02,
       -2.78624683e-01, -1.30459539e-01, -1.39699761e+00, -2.44713889e-01,
        8.30253911e-01,  2.40821202e-01, -9.15697123e-01, -2.22527996e+00,
       -6.63067012e-01, -3.21194764e-01,  4.98388165e-01,  3.80338976e-01,
       -1.06703532e+00,  2.55452172e-01,  2.11128719e+00, -6.34189962e-01,
        1.36875577e+00, -9.70649489e-01,  6.54245334e-01, -1.17189522e+00,
       -3.15987198e-03, -7.45604825e-01,  1.59829089e+00, -9.13399998e-01,
        2.40291209e+00, -5.89360262e-01,  1.07657442e-01, -1.39297516e-01,
       -1.15992573e+00,  6.18964782e-01,  1.37389047e+00, -9.83504717e-01,
        9.30943764e-01, -8.11675639e-01, -1.83015626e+00, -1.38730146e-01,
        3.34088351e-01,  4.88674994e-01, -1.78098226e-01,  2.12231470e+00,
        6.11919495e-02,  8.84110821e-01, -6.08505836e-01, -7.20516756e-02,
        5.44066287e-01,  3.23885545e-01, -1.68332517e+00,  5.26860435e-01,
        1.85879122e+00, -5.48419452e-01, -2.79397288e-01, -2.12989863e-02,
       -2.87990237e-01,  8.91745988e-02,  5.22857735e-01,  5.72796449e-01,
       -1.76037169e+00,  1.12817940e+00,  1.56860620e+00, -3.42277145e-01,
       -9.81300278e-03,  5.30717701e-02, -4.19434456e-02, -1.69431249e+00,
       -3.62380844e-01,  1.12745262e+00,  2.18383015e+00, -1.18662278e+00,
        3.34269695e-01, -1.02838881e+00, -1.68495578e-01, -9.98948357e-01,
       -1.53115136e+00, -1.07911108e+00, -1.09773190e+00,  4.05147557e-01,
       -2.27228189e-01, -1.44279215e+00, -1.42257533e+00, -1.12316481e+00,
        2.16205384e-01, -4.59849288e-01,  3.33391706e-01, -2.54742262e-01,
       -4.48301374e-01, -1.26134379e+00,  1.16514781e+00, -6.21249236e-01,
       -7.99318495e-01,  7.77233326e-01, -6.12904739e-01,  3.16446654e-01,
        8.38295224e-01, -1.03442316e+00,  4.34304038e-01, -2.21313325e+00,
        7.58040340e-01,  5.53932642e-01,  3.39230720e-01, -6.88756290e-01])

In [228]:
quartiles = pd.qcut(data, 4, precision=2)
quartiles

[(0.62, 3.93], (-2.96, -0.68], (0.62, 3.93], (0.62, 3.93], (0.62, 3.93], ..., (-2.96, -0.68], (0.62, 3.93], (-0.026, 0.62], (-0.026, 0.62], (-2.96, -0.68]]
Length: 1000
Categories (4, interval[float64, right]): [(-2.96, -0.68] < (-0.68, -0.026] < (-0.026, 0.62] < (0.62, 3.93]]

In [229]:
pd.value_counts(quartiles)

C:\Users\safye\AppData\Local\Temp\ipykernel_25508\3472704981.py:1: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  pd.value_counts(quartiles)

(-2.96, -0.68]     250
(-0.68, -0.026]    250
(-0.026, 0.62]     250
(0.62, 3.93]       250
Name: count, dtype: int64

In [230]:
pd.qcut(data, [0, 0.1, 0.5, 0.9, 1.]).value_counts()

(-2.9499999999999997, -1.187]    100
(-1.187, -0.0265]                400
(-0.0265, 1.287]                 400
(1.287, 3.928]                   100
Name: count, dtype: int64

### Aykırı Değerleri Tespit Etme ve Filtreleme

In [231]:
data = pd.DataFrame(np.random.standard_normal((1000, 4)))

In [232]:
data.describe()

                 0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean      0.045383     0.024079    -0.004794    -0.050389
std       0.997796     1.008737     0.996599     0.996706
min      -3.645860    -3.184377    -3.745356    -3.428254
25%      -0.600254    -0.612162    -0.697084    -0.747478
50%       0.040150    -0.013609    -0.029924    -0.088274
75%       0.746527     0.690847     0.699046     0.623331
max       2.653656     3.525865     2.735527     3.366626

In [233]:
col = data[2]
col

0      2.406483
1     -0.395813
2      0.329313
3      1.927640
4     -0.017905
         ...
995    1.128420
996   -2.314042
997   -1.839647
998   -0.138244
999   -0.111520
Name: 2, Length: 1000, dtype: float64

In [234]:
col[col.abs() > 3]

38    -3.399312
133   -3.745356
Name: 2, dtype: float64

In [235]:
data[(data.abs() > 3).any(axis="columns")]

            0         1         2         3
38   0.457246 -0.025907 -3.399312 -0.974657
57   1.951312  3.260383  0.963301  1.201206
133  0.508391 -0.196713 -3.745356 -1.520113
232 -0.242459 -3.056990  1.918403 -0.578828
255  0.682841  0.326045  0.425384 -3.428254
319  1.179227 -3.184377  1.369891 -1.074833
541 -3.548824  1.553205 -2.186301  1.277104
632 -0.578093  0.193299  1.397822  3.366626
779 -0.207434  3.525865  0.283070  0.544635
800 -3.645860  0.255475 -0.549574 -1.907459

In [236]:
data[data.abs() > 3] = np.sign(data)*3

In [237]:
data.describe()

                 0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean      0.046577     0.023534    -0.003650    -0.050328
std       0.993777     1.005496     0.992788     0.994152
min      -3.000000    -3.000000    -3.000000    -3.000000
25%      -0.600254    -0.612162    -0.697084    -0.747478
50%       0.040150    -0.013609    -0.029924    -0.088274
75%       0.746527     0.690847     0.699046     0.623331
max       2.653656     3.000000     2.735527     3.000000

In [238]:
np.sign(data).head()

     0    1    2    3
0 -1.0 -1.0  1.0 -1.0
1 -1.0  1.0 -1.0 -1.0
2  1.0 -1.0  1.0 -1.0
3  1.0 -1.0  1.0 -1.0
4 -1.0 -1.0 -1.0 -1.0

### Gösterge/Kukla (Dummy) Değişkenleri Hesaplama

In [239]:
df = pd.DataFrame({"key": ["b", "b", "a", "c", "a", "b"], "data1": range(6)})

In [240]:
df

  key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   b      5

In [241]:
pd.get_dummies(df["key"])

       a      b      c
0  False   True  False
1  False   True  False
2   True  False  False
3  False  False   True
4   True  False  False
5  False   True  False

In [242]:
dummies = pd.get_dummies(df["key"], prefix="key")

In [243]:
df_with_dumy = df[["data1"]].join(dummies)

In [244]:
df_with_dumy

   data1  key_a  key_b  key_c
0      0  False   True  False
1      1  False   True  False
2      2   True  False  False
3      3  False  False   True
4      4   True  False  False
5      5  False   True  False

In [245]:
mnames = ["movie_id", "title", "genres"]

In [246]:
mnames

['movie_id', 'title', 'genres']

In [247]:
movies = pd.read_table("C:/Users/safye/Downloads/pydata-book-3rd-edition/pydata-book-3rd-edition/datasets/movielens/movies.dat", 
                       sep="::", header=None, names=mnames, engine="python")

In [248]:
movies[:10]

   movie_id                               title                        genres
0         1                    Toy Story (1995)   Animation|Children's|Comedy
1         2                      Jumanji (1995)  Adventure|Children's|Fantasy
2         3             Grumpier Old Men (1995)                Comedy|Romance
3         4            Waiting to Exhale (1995)                  Comedy|Drama
4         5  Father of the Bride Part II (1995)                        Comedy
5         6                         Heat (1995)         Action|Crime|Thriller
6         7                      Sabrina (1995)                Comedy|Romance
7         8                 Tom and Huck (1995)          Adventure|Children's
8         9                 Sudden Death (1995)                        Action
9        10                    GoldenEye (1995)     Action|Adventure|Thriller

In [249]:
dummies = movies["genres"].str.get_dummies("|")

In [250]:
dummies.iloc[:10, :6]

   Action  Adventure  Animation  Children's  Comedy  Crime
0       0          0          1           1       1      0
1       0          1          0           1       0      0
2       0          0          0           0       1      0
3       0          0          0           0       1      0
4       0          0          0           0       1      0
5       1          0          0           0       0      1
6       0          0          0           0       1      0
7       0          1          0           1       0      0
8       1          0          0           0       0      0
9       1          1          0           0       0      0

In [251]:
dummies.iloc[:10]

,Action,Adventure,Animation,Children's,Comedy,Crime,Documentary,Drama,Fantasy,Film-Noir,Horror,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western
0,0,0,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0
1,0,1,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0
2,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0
3,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
5,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0
6,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0
7,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
8,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
9,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0

In [252]:
movies_windic = movies.join(dummies.add_prefix("Genre_"))
movies_windic.iloc[0]

movie_id                                       1
title                           Toy Story (1995)
genres               Animation|Children's|Comedy
Genre_Action                                   0
Genre_Adventure                                0
Genre_Animation                                1
Genre_Children's                               1
Genre_Comedy                                   1
Genre_Crime                                    0
Genre_Documentary                              0
Genre_Drama                                    0
Genre_Fantasy                                  0
Genre_Film-Noir                                0
Genre_Horror                                   0
Genre_Musical                                  0
Genre_Mystery                                  0
Genre_Romance                                  0
Genre_Sci-Fi                                   0
Genre_Thriller                                 0
Genre_War                                      0
Genre_Western                                  0
Name: 0, dtype: object

In [253]:
movies_windic

,movie_id,title,genres,Genre_Action,Genre_Adventure,Genre_Animation,Genre_Children's,Genre_Comedy,Genre_Crime,Genre_Documentary,...,Genre_Fantasy,Genre_Film-Noir,Genre_Horror,Genre_Musical,Genre_Mystery,Genre_Romance,Genre_Sci-Fi,Genre_Thriller,Genre_War,Genre_Western
0,1,Toy Story (1995),Animation|Children's|Comedy,0,0,1,1,1,0,0,...,0,0,0,0,0,0,0,0,0,0
1,2,Jumanji (1995),Adventure|Children's|Fantasy,0,1,0,1,0,0,0,...,1,0,0,0,0,0,0,0,0,0
2,3,Grumpier Old Men (1995),Comedy|Romance,0,0,0,0,1,0,0,...,0,0,0,0,0,1,0,0,0,0
3,4,Waiting to Exhale (1995),Comedy|Drama,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
4,5,Father of the Bride Part II (1995),Comedy,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3878,3948,Meet the Parents (2000),Comedy,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
3879,3949,Requiem for a Dream (2000),Drama,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3880,3950,Tigerland (2000),Drama,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3881,3951,Two Family House (2000),Drama,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3882,3952,"Contender, The (2000)",Drama|Thriller,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0

In [254]:
np.random.seed(12345)
values = np.random.uniform(size=10)

In [255]:
values

array([0.92961609, 0.31637555, 0.18391881, 0.20456028, 0.56772503,
       0.5955447 , 0.96451452, 0.6531771 , 0.74890664, 0.65356987])

In [256]:
bins = [0, 0.2, 0.4, 0.6, 0.8, 1]

In [257]:
pd.get_dummies(pd.cut(values, bins))

   (0.0, 0.2]  (0.2, 0.4]  (0.4, 0.6]  (0.6, 0.8]  (0.8, 1.0]
0       False       False       False       False        True
1       False        True       False       False       False
2        True       False       False       False       False
3       False        True       False       False       False
4       False       False        True       False       False
5       False       False        True       False       False
6       False       False       False       False        True
7       False       False       False        True       False
8       False       False       False        True       False
9       False       False       False        True       False

In [258]:
s = pd.Series([1, 2, 3, None])

In [259]:
s

0    1.0
1    2.0
2    3.0
3    NaN
dtype: float64

In [260]:
s.dtype

dtype('float64')

In [261]:
s = pd.Series([1, 2, 3, None], dtype=pd.Int64Dtype())

In [262]:
s

0       1
1       2
2       3
3    <NA>
dtype: Int64

In [263]:
s.isna()

0    False
1    False
2    False
3     True
dtype: bool

In [264]:
s.dtype

Int64Dtype()

In [265]:
s[3]

In [266]:
s[3] is pd.NA

True

In [267]:
s = pd.Series([1, 2, 3, None], dtype="Int64")

In [268]:
s

0       1
1       2
2       3
3    <NA>
dtype: Int64

In [269]:
s = pd.Series(['one', 'two', None, 'three'], dtype=pd.StringDtype())

In [270]:
s

0      one
1      two
2     <NA>
3    three
dtype: string

In [271]:
df = pd.DataFrame({"A": [1, 2, None, 4],
                   "B": ["one", "two", "three", None],
                    "C": [False, None, False, True]})

In [272]:
df

     A      B      C
0  1.0    one  False
1  2.0    two   None
2  NaN  three  False
3  4.0   None   True

In [273]:
df["A"] = df["A"].astype("Int64")

In [274]:
df["B"] = df["B"].astype("string")

In [275]:
df["C"] = df["C"].astype("boolean")

In [276]:
df

      A      B      C
0     1    one  False
1     2    two   <NA>
2  <NA>  three  False
3     4   <NA>   True

## 7.4 Dize Manipülasyonu

### Python Yerleşik Dize Nesnesi Metotları

In [277]:
val = "a, b, guido"

In [278]:
val

'a, b, guido'

In [279]:
val.split(",")

['a', ' b', ' guido']

In [280]:
pieces = [x.strip() for x in val.split(",")]

In [281]:
pieces

['a', 'b', 'guido']

In [282]:
first, second, third = pieces
first + "::" + second + "::" + third

'a::b::guido'

In [283]:
"::".join(pieces)

'a::b::guido'

In [284]:
"guido" in val

True

In [285]:
val.index(",")

1

In [286]:
val.find(":")

-1

In [287]:
val.count(",")

2

In [288]:
val.replace(",", "::")

'a:: b:: guido'

In [289]:
val.replace(",", "")

'a b guido'

### Düzenli İfadeler (Regular Expressions)

In [290]:
import re

In [291]:
text = "foo bar\t baz \tqux"
text

'foo bar\t baz \tqux'

In [292]:
re.split(r"\s+", text)

['foo', 'bar', 'baz', 'qux']

In [293]:
regex = re.compile(r"\s+")
regex.split(text)

['foo', 'bar', 'baz', 'qux']

In [294]:
regex.findall(text)

[' ', '\t ', ' \t']

In [295]:
text = """Dave dave@google.com
Steve steve@gmail.com
Rob rob@gmail.com
Ryan ryan@yahoo.com"""

pattern = r"[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}"

In [296]:
# re.IGNORECASE regex'i büyük/küçük harfe duyarsız hale getirir
regex = re.compile(pattern, flags=re.IGNORECASE)

In [297]:
regex.findall(text)

['dave@google.com', 'steve@gmail.com', 'rob@gmail.com', 'ryan@yahoo.com']

In [298]:
m = regex.search(text)
m

In [299]:

text[m.start():m.end()]

'dave@google.com'

In [300]:
print(regex.match(text))

None

In [301]:
print(regex.sub("REDACTED", text))

Dave REDACTED
Steve REDACTED
Rob REDACTED
Ryan REDACTED

In [302]:
pattern = r"([A-Z0-9._%+-]+)@([A-Z0-9.-]+)\.([A-Z]{2,4})"
regex = re.compile(pattern, flags=re.IGNORECASE)

In [305]:
m = regex.match("wesm@bright.net")
m.groups()

('wesm', 'bright', 'net')

In [306]:
regex.findall(text)

[('dave', 'google', 'com'),
 ('steve', 'gmail', 'com'),
 ('rob', 'gmail', 'com'),
 ('ryan', 'yahoo', 'com')]

In [307]:
print(regex.sub(r"Username: \1, Domain: \2, Suffix: \3", text))

Dave Username: dave, Domain: google, Suffix: com
Steve Username: steve, Domain: gmail, Suffix: com
Rob Username: rob, Domain: gmail, Suffix: com
Ryan Username: ryan, Domain: yahoo, Suffix: com