In [2]:
import numpy as np
import pandas as pd

### 7.1 Eksik Verilerle Başa Çıkma

In [3]:
float_data = pd.Series([1.2, -3.5, np.nan, 0])
float_data

0    1.2
1   -3.5
2    NaN
3    0.0
dtype: float64

In [4]:
float_data.isna()

0    False
1    False
2     True
3    False
dtype: bool

In [5]:
pd.isna(float_data)

0    False
1    False
2     True
3    False
dtype: bool

In [6]:
string_data = pd.Series(["aardvark", np.nan, None, "avocado"])
string_data

0    aardvark
1         NaN
2        None
3     avocado
dtype: object

In [7]:
string_data.isna()

0    False
1     True
2     True
3    False
dtype: bool

In [8]:
float_data = pd.Series([1, 2, None], dtype='float64')

In [9]:
float_data

0    1.0
1    2.0
2    NaN
dtype: float64

In [10]:
float_data.isna()

0    False
1    False
2     True
dtype: bool

### Eksik Verileri Filtreleme

In [11]:
data = pd.Series([1, np.nan, 3.5, np.nan, 7])
data.dropna()

0    1.0
2    3.5
4    7.0
dtype: float64

In [12]:
data[data.notna()]

0    1.0
2    3.5
4    7.0
dtype: float64

In [13]:
data = pd.DataFrame([[1., 6.5, 3.], [1., np.nan, np.nan],
                     [np.nan, np.nan, np.nan], [np.nan, 6.5, 3.]])

In [14]:
data

     0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [15]:
data.dropna()

     0    1    2
0  1.0  6.5  3.0

In [16]:
data.dropna(how="all")

     0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
3  NaN  6.5  3.0

In [17]:
data.dropna(how="any")

     0    1    2
0  1.0  6.5  3.0

In [18]:
data[4] = np.nan
data

     0    1    2   4
0  1.0  6.5  3.0 NaN
1  1.0  NaN  NaN NaN
2  NaN  NaN  NaN NaN
3  NaN  6.5  3.0 NaN

In [19]:
data.dropna(axis="columns", how="all")

     0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [20]:
data.dropna(axis="columns", how="any")

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3]

In [21]:
df = pd.DataFrame(np.random.standard_normal((7,3)))

In [22]:
df

          0         1         2
0  1.214800  1.490341 -0.014231
1 -0.642942  0.633448  0.265822
2 -0.632720 -0.891057  0.799905
3  0.065669  0.872098 -0.808984
4 -0.694572 -1.827990 -0.196298
5 -0.226798 -1.782885 -0.453463
6  2.763483  0.029056 -0.544274

In [23]:
df.iloc[:4, 1] = np.nan

In [24]:
df.iloc[:2, 2]= np.nan

In [25]:
df

          0         1         2
0  1.214800       NaN       NaN
1 -0.642942       NaN       NaN
2 -0.632720       NaN  0.799905
3  0.065669       NaN -0.808984
4 -0.694572 -1.827990 -0.196298
5 -0.226798 -1.782885 -0.453463
6  2.763483  0.029056 -0.544274

In [26]:
df.dropna()

          0         1         2
4 -0.694572 -1.827990 -0.196298
5 -0.226798 -1.782885 -0.453463
6  2.763483  0.029056 -0.544274

In [27]:
df.dropna(how="all")

          0         1         2
0  1.214800       NaN       NaN
1 -0.642942       NaN       NaN
2 -0.632720       NaN  0.799905
3  0.065669       NaN -0.808984
4 -0.694572 -1.827990 -0.196298
5 -0.226798 -1.782885 -0.453463
6  2.763483  0.029056 -0.544274

In [28]:
df.dropna(thresh=2)

          0         1         2
2 -0.632720       NaN  0.799905
3  0.065669       NaN -0.808984
4 -0.694572 -1.827990 -0.196298
5 -0.226798 -1.782885 -0.453463
6  2.763483  0.029056 -0.544274

In [29]:
df.dropna(thresh=1)

          0         1         2
0  1.214800       NaN       NaN
1 -0.642942       NaN       NaN
2 -0.632720       NaN  0.799905
3  0.065669       NaN -0.808984
4 -0.694572 -1.827990 -0.196298
5 -0.226798 -1.782885 -0.453463
6  2.763483  0.029056 -0.544274

### Eksik Verileri Doldurma

In [30]:
df.fillna(0)

          0         1         2
0  1.214800  0.000000  0.000000
1 -0.642942  0.000000  0.000000
2 -0.632720  0.000000  0.799905
3  0.065669  0.000000 -0.808984
4 -0.694572 -1.827990 -0.196298
5 -0.226798 -1.782885 -0.453463
6  2.763483  0.029056 -0.544274

In [31]:
df.fillna({1: 0.5, 2: 0})

          0         1         2
0  1.214800  0.500000  0.000000
1 -0.642942  0.500000  0.000000
2 -0.632720  0.500000  0.799905
3  0.065669  0.500000 -0.808984
4 -0.694572 -1.827990 -0.196298
5 -0.226798 -1.782885 -0.453463
6  2.763483  0.029056 -0.544274

In [32]:
df = pd.DataFrame(np.random.standard_normal((6,3)))
df.iloc[2:, 1] = np.nan
df.iloc[4:, 2] = np.nan

In [33]:
df

          0         1         2
0 -1.093256 -0.423403  0.359065
1  0.733397 -1.174644  1.747610
2 -0.422031       NaN -0.579264
3  0.037658       NaN -0.204776
4 -0.325673       NaN       NaN
5  0.788593       NaN       NaN

In [34]:
df.fillna(method="ffill")

C:\Users\safye\AppData\Local\Temp\ipykernel_3096\3944122520.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method="ffill")

          0         1         2
0 -1.093256 -0.423403  0.359065
1  0.733397 -1.174644  1.747610
2 -0.422031 -1.174644 -0.579264
3  0.037658 -1.174644 -0.204776
4 -0.325673 -1.174644 -0.204776
5  0.788593 -1.174644 -0.204776

In [35]:
data = pd.Series([1., np.nan, 3.5, np.nan, 7])
data

0    1.0
1    NaN
2    3.5
3    NaN
4    7.0
dtype: float64

In [36]:
data.fillna(data.mean())

0    1.000000
1    3.833333
2    3.500000
3    3.833333
4    7.000000
dtype: float64

### 7.2 Veri Dönüştürme

In [37]:
data = pd.DataFrame({"k1": ["one", "two"] * 3 + ["two"],
                     "k2": [1, 1, 2, 3, 3, 4, 4]})

In [38]:
data

    k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4
6  two   4

In [39]:
data.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6     True
dtype: bool

In [40]:
data.drop_duplicates()

    k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4

In [41]:
data["v1"] = range(7)
data

    k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
5  two   4   5
6  two   4   6

In [42]:
data.drop_duplicates(subset=["k1"])

    k1  k2  v1
0  one   1   0
1  two   1   1

### Bir Fonksiyon veya Eşleme Kullanarak Veri Dönüştürme

In [43]:
data = pd.DataFrame({"food": ["bacon", "pulled pork", "bacon",
                              "pastrami", "corned beef", "bacon",
                              "pastrami", "honey ham", "nova lox"],
                              "ounces": [4, 3, 12, 6, 7.5, 8, 3, 5, 6]})

In [44]:
data

          food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3     pastrami     6.0
4  corned beef     7.5
5        bacon     8.0
6     pastrami     3.0
7    honey ham     5.0
8     nova lox     6.0

In [45]:
meat_to_animal = {
 "bacon": "pig",
 "pulled pork": "pig",
 "pastrami": "cow",
 "corned beef": "cow",
 "honey ham": "pig",
 "nova lox": "salmon"
}

In [46]:
data["animal"] = data["food"].map(meat_to_animal)
data

          food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     pastrami     6.0     cow
4  corned beef     7.5     cow
5        bacon     8.0     pig
6     pastrami     3.0     cow
7    honey ham     5.0     pig
8     nova lox     6.0  salmon

In [47]:
def get_animal(x):
    return meat_to_animal[x]

In [48]:
data["food"].map(get_animal)

0       pig
1       pig
2       pig
3       cow
4       cow
5       pig
6       cow
7       pig
8    salmon
Name: food, dtype: object

In [49]:
data = pd.Series([1., -999., 2., -999., -1000., 3.])

In [50]:
data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [51]:
data.replace(-999, np.nan)

0       1.0
1       NaN
2       2.0
3       NaN
4   -1000.0
5       3.0
dtype: float64

In [52]:
data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [53]:
data.replace([-999, -1000], np.nan)

0    1.0
1    NaN
2    2.0
3    NaN
4    NaN
5    3.0
dtype: float64

In [54]:
data.replace([-999, -1000], [np.nan, 0])

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [55]:
data.replace({-999: np.nan, -1000: 0})

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

### Eksen İndekslerini Yeniden Adlandırma

In [56]:
data = pd.DataFrame(np.arange(12).reshape((3, 4)),
                    index=["Ohio", "Colorado", "New York"],
                    columns=["one", "two", "three", "four"])

In [57]:
def transform(x):
    return x[:4].upper()

In [58]:
data.index.map(transform)

Index(['OHIO', 'COLO', 'NEW '], dtype='object')

In [59]:
data.index = data.index.map(transform)

In [60]:
data

      one  two  three  four
OHIO    0    1      2     3
COLO    4    5      6     7
NEW     8    9     10    11

### Ayrıklaştırma ve Gruplandırma (Binning)

In [61]:
ages = [20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32]

In [62]:
bins = [18, 25, 35, 60, 100]
age_categories = pd.cut(ages, bins)

In [63]:
age_categories

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64, right]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [64]:
age_categories.codes

array([0, 0, 0, 1, 0, 0, 2, 1, 3, 2, 2, 1], dtype=int8)

In [65]:
age_categories.categories

IntervalIndex([(18, 25], (25, 35], (35, 60], (60, 100]], dtype='interval[int64, right]')

In [66]:
age_categories.categories[0]

Interval(18, 25, closed='right')

In [67]:
pd.value_counts(age_categories)

C:\Users\safye\AppData\Local\Temp\ipykernel_3096\3010498523.py:1: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  pd.value_counts(age_categories)

(18, 25]     5
(25, 35]     3
(35, 60]     3
(60, 100]    1
Name: count, dtype: int64

In [68]:
pd.cut(ages, bins, right=False)

[[18, 25), [18, 25), [25, 35), [25, 35), [18, 25), ..., [25, 35), [60, 100), [35, 60), [35, 60), [25, 35)]
Length: 12
Categories (4, interval[int64, left]): [[18, 25) < [25, 35) < [35, 60) < [60, 100)]

In [69]:
group_names = ["yputh", "YoungAdult", "MiddleAged", "Senior"]

In [70]:
pd.cut(ages, bins, labels=group_names)

['yputh', 'yputh', 'yputh', 'YoungAdult', 'yputh', ..., 'YoungAdult', 'Senior', 'MiddleAged', 'MiddleAged', 'YoungAdult']
Length: 12
Categories (4, object): ['yputh' < 'YoungAdult' < 'MiddleAged' < 'Senior']

In [71]:
data = np.random.uniform(size=20)
data

array([0.1761094 , 0.03818311, 0.17089157, 0.75367913, 0.25162315,
       0.58100713, 0.3470925 , 0.16211236, 0.03648438, 0.86313073,
       0.64714642, 0.28015383, 0.0730047 , 0.03452332, 0.03334026,
       0.86932634, 0.36544113, 0.58974996, 0.37075226, 0.80468127])

In [72]:
pd.cut(data, 4, precision=2)

[(0.033, 0.24], (0.033, 0.24], (0.033, 0.24], (0.66, 0.87], (0.24, 0.45], ..., (0.66, 0.87], (0.24, 0.45], (0.45, 0.66], (0.24, 0.45], (0.66, 0.87]]
Length: 20
Categories (4, interval[float64, right]): [(0.033, 0.24] < (0.24, 0.45] < (0.45, 0.66] < (0.66, 0.87]]

In [73]:
pd.value_counts(pd.cut(data, 4, precision=2))

C:\Users\safye\AppData\Local\Temp\ipykernel_3096\3248861558.py:1: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  pd.value_counts(pd.cut(data, 4, precision=2))

(0.033, 0.24]    8
(0.24, 0.45]     5
(0.66, 0.87]     4
(0.45, 0.66]     3
Name: count, dtype: int64

In [74]:
data = np.random.standard_normal(1000)
data

array([-2.03019668e-01,  2.43589285e-02,  3.89604156e-01,  4.78957501e-01,
        7.76693544e-01,  2.17916888e+00,  1.42441481e+00,  3.96307090e-01,
       -9.25746812e-01,  1.46054544e+00,  1.37930646e+00,  1.28721587e+00,
       -8.78684882e-01, -8.30334394e-01,  1.62799701e-01, -2.60510078e-01,
       -6.71163000e-02, -2.68772071e-01, -3.41993601e-01, -1.78844156e+00,
       -1.01797056e+00,  2.31441592e-01, -1.24967338e+00,  7.71058718e-01,
        1.47418212e+00,  2.72585208e-02, -8.81496761e-01,  7.58314078e-01,
       -9.94903457e-01, -2.35341269e+00,  1.38166317e-03, -1.70222181e+00,
       -6.89894882e-01, -2.03055501e+00, -7.26300988e-01,  3.59462710e-01,
       -1.64497876e+00, -1.64585695e+00,  6.16698906e-01, -8.87021510e-01,
       -1.97505541e+00,  1.54895016e-01,  4.75720204e-01, -2.27398361e-01,
        1.49582197e-01,  2.57246851e+00, -4.05487820e-01, -2.07011158e+00,
       -9.81148806e-01,  1.41529012e+00,  6.97358166e-01, -9.31763571e-01,
        1.53489030e+00, -3.35721716e-01,  4.51376409e-01,  3.91806553e-01,
        5.57148599e-01, -4.36315244e-01, -1.67881082e+00, -1.74988224e+00,
        9.88431488e-01, -2.12227852e-01,  3.27861445e+00,  3.94338158e-01,
       -1.07164154e+00,  5.79275971e-01, -1.72082654e+00,  1.39641814e-02,
       -5.41757692e-01, -1.03030108e+00,  5.71106726e-01,  8.68871458e-01,
        2.03503129e-02,  1.68845299e-01,  5.48570817e-01,  1.27858417e+00,
       -8.21813622e-01, -6.63082749e-01, -2.26067993e-02, -9.64376162e-01,
       -1.08707313e+00, -9.59147783e-01, -9.42841739e-01, -5.95654292e-01,
       -1.53085981e+00, -8.87037399e-01,  1.18691134e+00, -8.83932260e-01,
       -1.53082611e+00, -3.31170550e-01,  9.16211460e-01,  1.32414308e+00,
       -8.32527989e-01, -1.13254898e+00,  4.24485510e-01, -1.23987973e-01,
       -8.87096043e-01,  1.32055508e+00, -3.00937207e-01, -1.75681774e+00,
        1.58894791e+00,  6.56262411e-02,  4.11764834e-01, -2.88402413e-01,
       -2.52670449e-01,  1.33637801e+00,  1.47874660e+00,  2.98746822e-01,
       -5.53389992e-01,  5.07345997e-01, -6.00562079e-01, -3.75907387e-01,
        1.12547235e+00,  5.35692054e-01,  1.90581400e-02,  1.54801202e+00,
       -8.39217458e-02,  2.27236108e+00, -1.42292005e-01, -6.47409416e-02,
        1.32772388e+00,  1.57900517e+00, -1.05134933e+00, -8.64523268e-02,
        1.19482228e+00,  5.06857580e-01, -1.23824461e+00, -1.03104937e-01,
       -9.30164645e-01, -1.52164601e+00,  1.17649992e+00, -1.33262286e+00,
       -2.75086074e-01,  5.43211119e-01,  1.44483127e+00, -3.64523543e-02,
       -1.37162735e+00, -2.45899910e+00,  5.89841321e-01, -4.38514189e-01,
        6.90187963e-01, -9.22048909e-02, -1.91276658e+00, -7.70329919e-01,
       -1.16244726e+00, -4.50300249e-02,  1.48987722e+00, -4.83872299e-01,
       -1.58830828e+00,  1.05152087e+00, -5.08511837e-01,  1.41669318e+00,
       -8.76903507e-01, -1.20867489e+00,  6.31612746e-02, -2.92070567e-01,
        6.68144685e-01, -3.09960849e-01, -2.45404791e+00,  5.86798878e-01,
        1.14333620e+00,  1.87390434e-01,  1.37857834e+00, -8.31746466e-01,
        4.53101691e-01,  6.30272793e-02,  7.75183481e-01, -6.85008138e-01,
        7.49157679e-01,  6.79312119e-01, -8.89025351e-01,  1.60389919e+00,
       -5.95268187e-01, -1.12553346e+00,  1.02149988e-01,  8.33547274e-01,
       -4.20559317e-01,  1.15678339e+00,  3.02653334e-01,  2.66449859e+00,
        4.65893187e-01,  4.89698805e-01,  1.93877360e-01, -2.53130741e-01,
       -3.18451046e-01, -2.32168195e-01, -2.07158876e-01,  4.82579232e-02,
        5.88243888e-01,  1.34185905e-01, -6.34212871e-01,  3.45722569e-01,
        7.94552333e-01,  1.06891303e+00,  6.97381992e-01,  2.86029973e+00,
        1.04597906e+00, -4.46314220e-01, -4.85086618e-01,  1.17851056e-01,
        3.79723226e-01, -6.56405490e-02, -7.09681206e-01,  3.03102427e-01,
        6.51096687e-01,  7.14375358e-01,  2.41173895e-01, -2.00246427e+00,
        8.38911051e-01,  1.01506044e+00, -4.51118156e-01, -9.77008533e-01,
       -4.55458473e-02,  9.93579069e-02, -1.84022090e+00,  2.02397947e+00,
        1.39631831e+00,  3.00477983e-01, -3.73027222e-01, -1.28087477e+00,
       -1.23628995e+00,  4.55603666e-01,  3.24980773e-01, -6.19572990e-01,
       -8.21722656e-01,  1.52979488e+00,  1.33870703e+00, -4.04351697e-01,
       -6.61299849e-01, -8.03302788e-01, -6.64292625e-01, -1.66012226e-01,
       -1.49227322e+00, -1.12059492e-01, -4.98366757e-01, -9.60642151e-01,
        6.18119227e-01, -1.13357907e+00,  1.84764045e+00, -3.80342217e-02,
       -5.42976153e-01,  1.75209776e-01,  9.00037332e-01, -4.00544793e-01,
        7.17762468e-01,  2.16879853e-01,  1.97238461e+00, -5.87527058e-02,
       -4.01566843e-01,  3.52458953e-01, -1.35846381e+00,  1.25848235e+00,
        3.00109106e-01,  6.79551159e-01, -6.83101014e-01,  7.73366720e-01,
       -8.57824147e-01, -7.28865274e-01, -1.18481975e+00,  7.25973658e-01,
       -2.26488258e+00, -7.12922899e-01, -2.91538361e-01, -3.51772551e-01,
        1.99849971e+00, -9.39169416e-01,  7.61035530e-02, -2.99667467e-01,
       -9.02679606e-01,  2.08199465e-01, -9.72640059e-01, -2.23747530e-01,
        6.20484348e-01, -1.07347815e+00, -2.09638911e-01, -9.53256267e-02,
       -3.97781589e-01,  8.08462646e-01, -8.75788818e-01,  6.77115716e-01,
       -8.24462098e-02,  2.59804127e-01, -1.23988154e+00, -1.94588856e-01,
        1.40372829e+00,  5.00084250e-01, -9.41689040e-01,  8.28628963e-01,
        8.13720649e-01,  8.94505878e-01, -6.34176684e-01, -1.91783974e+00,
        1.14253849e+00,  4.55438933e-01,  7.70067168e-01,  5.87548801e-01,
       -4.16451719e-01, -9.07202808e-01, -7.94053767e-02, -5.79495707e-01,
        6.42083813e-01, -1.11751864e+00,  3.81824971e-01, -6.62103179e-03,
       -1.25692440e+00,  2.43033312e-01,  1.38597903e+00, -9.84824872e-01,
       -1.88792406e+00, -1.81622978e+00,  1.13974032e+00,  4.97126081e-01,
        1.85187380e+00,  6.85253322e-01, -1.74320463e+00,  7.52320049e-01,
       -8.58648236e-01,  1.77149848e-02,  6.30946815e-01,  7.11560557e-01,
        2.03346841e+00,  5.91160172e-01, -2.97765184e-03, -6.19996297e-01,
        9.58450002e-01, -4.32756255e-01, -1.48597724e+00,  5.82304781e-01,
       -1.89519110e+00,  1.13152179e-01, -3.88509194e-02,  2.21415674e-01,
        9.86946740e-01,  7.20996918e-01, -2.81286946e-02,  2.10435321e+00,
        1.41401027e-01,  8.74733707e-01, -1.11577903e+00, -7.00732009e-01,
        2.69765490e-01, -6.60059278e-01,  7.53978767e-01, -1.85988029e+00,
       -1.69649546e-01,  2.32019185e+00,  5.87117663e-01,  9.21343576e-01,
        2.78122539e-01,  7.89769080e-01,  8.18282637e-01, -5.58137508e-01,
        3.48956252e-02,  9.41544482e-01, -9.96533617e-01,  3.17546091e-01,
        7.47532717e-01,  8.32605794e-01, -1.38291536e+00, -6.97781627e-01,
       -2.34058317e-01,  3.82573317e-01,  2.20714562e+00,  2.15697356e+00,
       -1.95245628e-01, -1.69826031e-01,  6.04041215e-01,  3.67592738e-01,
        4.09712339e-01, -1.07699100e+00, -1.29734844e+00, -2.03936985e-01,
        1.58843255e+00,  2.73099591e-01,  7.90046077e-01,  3.13860396e-01,
       -1.43710839e+00, -1.35800618e-01, -8.52419945e-01,  2.10836761e-01,
       -4.23059053e-01, -2.03510324e+00,  4.25402432e-01, -1.82963625e+00,
       -1.71343442e+00, -1.23658608e+00,  1.06318980e+00, -7.72993394e-02,
        6.15964676e-01, -1.25060536e+00, -1.02757674e+00, -1.20082055e-01,
       -5.28070303e-01,  5.11442072e-02,  4.66435596e-01,  6.58531437e-01,
        1.05419137e+00, -5.25997798e-02,  1.60988415e+00,  7.79657101e-01,
       -3.98304767e-02,  1.50211131e-01,  5.52244998e-01,  2.32425218e+00,
       -9.30649319e-01,  2.43897454e+00, -5.18938855e-01,  6.95722769e-01,
        3.88238890e-01,  1.37715303e-01, -6.62884396e-01, -5.64283025e-01,
        7.50814577e-01, -1.94630057e-01, -7.38411953e-01,  1.71112409e+00,
       -1.21956997e+00, -1.17894185e+00, -9.55895005e-01, -8.30022801e-01,
        1.03616675e+00, -4.09040194e-01,  2.74448625e-01, -1.20178490e+00,
       -8.19422335e-01, -1.48200322e+00,  9.94715389e-01,  2.88353165e-02,
        2.10056508e+00,  1.85339780e+00,  2.42746602e+00, -1.16365428e+00,
        4.97172393e-01,  1.04172976e+00, -7.29826653e-01,  4.53071802e-02,
        1.23918872e-01,  5.05121417e-01, -1.98020876e+00, -1.28885554e+00,
       -1.86394336e+00, -4.84392831e-01,  1.15005015e+00,  1.09744583e-01,
       -7.25117646e-01,  8.65021944e-01,  4.05038289e-01,  1.32816372e-01,
        1.53054914e+00, -1.05645770e+00,  9.52609462e-01,  5.74739920e-01,
        1.30898066e+00,  4.75646547e-01, -3.68311572e-01, -3.94068872e-01,
       -1.12583449e+00,  1.54520531e+00, -7.75903939e-02,  2.26684965e+00,
       -1.39603400e-01,  2.85556789e-01,  1.37307422e+00, -2.96401393e-01,
        2.49814659e+00, -9.62419857e-01,  1.58822306e-01,  6.81942298e-01,
       -6.42990037e-01,  7.28082444e-01, -3.12526974e-01,  8.07964869e-01,
        1.08333058e+00, -4.05669991e-01,  2.02745636e+00, -1.22700133e+00,
        7.09798840e-01,  6.26036896e-01, -3.40228109e-01,  9.24257513e-01,
        1.17205953e+00,  5.28275203e-01,  4.44534967e-01,  5.02803834e-01,
        1.17271271e-01,  1.23564333e+00,  4.30028515e-01, -2.17277490e-01,
       -4.03481729e-01, -1.28663905e+00, -2.89026730e-01, -1.35126258e+00,
        1.23904381e+00, -1.21394002e+00, -9.88949540e-01, -4.47737091e-01,
        1.00514909e+00,  7.46363102e-01,  3.85958504e-01, -3.79769195e-01,
        7.12981422e-01,  2.17460683e+00, -7.14419948e-01,  2.65619484e-02,
       -4.88554893e-01,  5.91716992e-01, -1.73104150e+00, -2.60525792e-01,
       -6.89991774e-01,  1.52205683e-01,  6.69265745e-01,  4.36474717e-01,
        5.36076791e-01,  1.32927924e+00,  6.38467704e-01,  1.45115164e+00,
       -2.04456061e-01,  1.51741960e+00, -6.73750195e-01, -2.38509774e-01,
        6.52269201e-02, -2.76884218e-01, -1.03369514e+00, -1.16776025e-01,
        3.16186516e-01,  8.47529624e-01, -1.22052599e+00,  9.45204033e-01,
       -9.12348640e-01, -2.39624265e-01,  3.95764886e-01, -1.84237590e-01,
       -3.12031507e-01,  1.08865733e+00,  5.76657563e-01,  7.82569587e-01,
        7.74705628e-01, -4.06075960e-01, -5.99744496e-01, -5.08735995e-01,
       -4.71216228e-02,  1.27489625e+00, -4.97914054e-01,  1.00170718e+00,
        1.36062867e+00,  1.19365417e+00, -3.70461138e-01, -9.31591774e-02,
       -2.59521199e-01, -1.56302905e-01,  2.99693460e-01, -7.00037759e-01,
        5.84781367e-01, -4.58021374e-01,  1.64267978e+00, -4.53398915e-01,
        5.96759088e-01, -2.19922294e-03, -6.97284768e-01,  1.35593276e+00,
       -1.29233166e-01, -4.53329021e-01, -2.11718160e-02,  1.81344489e+00,
        3.52552041e-01, -4.77541285e-01,  1.53152231e+00,  2.28362596e+00,
        9.61483489e-01,  2.92367417e-01,  2.00015970e+00,  8.63883388e-01,
       -1.03078702e+00,  1.40477730e+00, -9.59116647e-01,  1.13630125e+00,
       -4.96412799e-03, -1.04681786e+00,  3.45357421e-01,  1.45647322e+00,
       -2.25803143e-02,  4.79641375e-01, -2.09260912e-01,  7.93850615e-01,
        1.26253212e+00, -2.28453704e-01,  6.96057411e-02,  5.56381063e-01,
       -1.32712338e+00,  3.65230064e+00, -1.05760268e-01,  9.91348298e-01,
       -3.85444827e-01, -2.19689391e-01, -6.63315644e-01, -2.65232719e-01,
        7.78488070e-01,  9.37450502e-01, -1.14371645e+00,  4.96743023e-02,
       -2.98991226e-01, -4.05086181e-01,  1.09657285e-01, -1.02986106e+00,
       -1.15535290e-01,  4.01271122e-01, -2.01668786e-02,  6.55665363e-01,
       -3.27711342e-02,  4.95023363e-01,  7.62000616e-01,  8.69039381e-01,
       -1.27092529e+00,  1.57206057e+00,  1.10910881e+00, -1.25401760e+00,
       -1.12108506e+00,  1.93617703e-02,  6.23512477e-02, -4.44946627e-01,
        1.28329329e-01,  2.84358929e-01, -6.50788374e-01, -1.01771611e+00,
        3.63773017e-01, -2.27962808e+00, -6.74454582e-01,  2.97495905e-01,
       -3.98399200e-01,  1.47366059e+00, -7.11480934e-01,  8.52460906e-02,
        1.16799434e+00,  1.08948049e+00, -1.33835528e-01, -6.93404045e-01,
       -8.12760715e-01,  4.59824748e-01,  3.98118460e-01, -1.84818279e-01,
       -6.18327619e-01,  8.31457500e-01, -5.20879142e-01,  7.12723138e-02,
       -2.92053286e+00,  4.81633175e-01,  7.08273430e-02,  4.68277922e-01,
       -1.46803547e+00,  9.48512047e-02,  1.32288338e-01, -6.42850898e-02,
        1.57973307e-01,  1.15101388e+00, -1.14084826e+00,  2.45649711e-01,
        2.67884122e-01, -1.49179685e+00, -1.07318951e+00,  1.60931768e+00,
       -1.51098182e+00, -2.36254788e-01, -2.94479625e-01,  7.21599957e-01,
        1.36051179e+00,  8.83674062e-01,  1.15571878e+00, -1.37894170e+00,
       -2.75241469e-01,  1.27231861e+00, -1.14618254e+00,  4.79619707e-02,
       -1.45032095e+00,  7.50391963e-01, -4.17011986e-01, -1.00940570e+00,
        9.99722596e-01,  1.28526263e+00, -2.19943838e+00, -1.19926357e+00,
       -2.37222228e-01,  6.37686169e-01, -4.61658696e-01,  1.05623322e+00,
       -7.19694906e-01, -7.38238697e-01,  3.16538275e-02, -4.25913064e-01,
        1.09875219e+00, -6.63520289e-01, -1.69518929e+00,  1.08715912e+00,
        7.15237221e-01, -1.80014876e+00, -1.23970437e+00, -1.67850321e+00,
       -4.72485316e-03, -2.17217397e-01, -1.83958166e+00,  5.20601915e-01,
        4.67598982e-01, -1.17659969e-01,  6.58049350e-01, -9.70049859e-01,
       -1.20670448e+00,  9.61279764e-01, -9.50782040e-01,  4.74207325e-01,
        2.51044117e-01,  1.53969980e+00, -1.26639149e+00,  7.38207104e-01,
       -5.63033694e-01,  1.82430069e+00, -7.76459836e-02,  6.07474573e-01,
        7.58279060e-01,  2.59404710e-01, -1.50148883e+00,  7.82534152e-01,
        4.58789393e-01, -2.95210526e-01, -2.07542628e-01, -5.33255314e-01,
        1.57446564e+00,  7.49191349e-02,  5.35868398e-03, -1.24816055e+00,
        1.58246923e+00,  1.25340870e-01,  7.38073241e-01, -1.70680351e+00,
        1.18070389e+00,  2.14242808e-01,  3.73627342e-01,  1.91645655e+00,
        1.66661834e+00, -8.95620913e-01, -1.04370606e+00,  1.23839193e+00,
       -1.08795037e+00,  5.88483596e-01, -3.14225625e-01,  1.23683964e+00,
       -1.68113950e+00, -7.75161666e-01, -2.90587736e-02, -5.53172424e-01,
       -6.40221877e-01,  2.44873087e-02,  6.57103342e-01,  1.26432108e+00,
       -1.47326526e+00,  6.35414226e-01, -8.58393870e-01,  3.52412245e-02,
        8.63918598e-01,  7.93953187e-01,  1.20793141e+00,  4.33510609e-01,
        5.65630647e-01, -4.40906344e-01,  1.69137626e+00,  2.57368762e+00,
        1.16962122e+00,  2.84687886e-01, -1.39949424e-01,  8.63008685e-02,
        2.21601444e-01,  5.34227196e-01, -1.79630034e+00,  6.40964670e-01,
        1.05098367e+00, -1.22076732e+00, -2.05773699e+00,  1.90501803e+00,
       -2.21441661e+00, -6.33867777e-01, -6.21011274e-01, -7.02796619e-01,
        2.30331743e-02, -2.01239338e+00, -1.46114369e+00, -1.95180451e-01,
        9.57572289e-01, -1.12837536e+00, -6.59132931e-01, -1.89649205e+00,
        8.52441892e-01,  1.17034237e+00,  4.64955754e-01, -1.06773152e+00,
       -4.73861147e-01, -6.84843256e-01, -9.99934582e-02, -1.93650577e-01,
        2.71636958e-01, -7.49852050e-02,  8.24656809e-01,  3.19073803e-01,
       -4.20414672e-01, -5.53549761e-01, -4.46306221e-01, -7.49697437e-02,
        3.20520709e-02, -1.63375696e-01, -5.72640843e-01, -1.03654607e+00,
       -1.26492945e+00, -1.00015519e+00,  1.43328983e-01, -4.62129130e-01,
        2.36908398e+00,  7.76051676e-01,  5.51137873e-01,  1.26699681e+00,
       -4.90227186e-01, -3.09932063e-01, -1.10460643e+00, -4.53684455e-02,
       -3.28619077e-01,  9.22438234e-01,  4.49395731e-01, -2.30494412e+00,
        1.65658178e+00, -1.99350181e+00, -5.02682735e-01,  1.93893658e-02,
       -1.77302913e-01, -8.43034879e-02,  2.82696393e-01, -9.09737666e-01,
        1.15357140e-01,  5.81047646e-01, -8.49267666e-01,  2.34608886e+00,
       -9.79652201e-01,  6.07793741e-01,  3.82849280e-01,  1.53239437e+00,
       -8.89028318e-01, -1.09284138e+00,  1.41439528e+00,  2.69783377e+00,
        7.56555329e-01,  2.84485103e-01,  7.20201520e-01, -6.56971962e-01,
        6.82203786e-01, -9.70497985e-01, -8.78892939e-02,  4.86736606e-01,
        9.20801416e-01, -1.82336624e-01,  1.00396131e+00,  1.80200231e+00,
       -9.24800913e-01,  1.19299536e-01,  1.88577839e-01, -4.12447340e-01,
       -1.40686438e+00, -7.16699355e-01, -1.91671838e-01, -8.63922042e-01,
       -7.14393447e-01,  7.45310209e-01,  1.16135552e+00,  1.50104982e+00,
        2.24898375e-01, -8.50510286e-01, -5.59700154e-01, -6.47324446e-01,
        1.59996722e-01,  1.71062027e+00, -2.40239716e-01, -7.48891483e-01,
        3.79496135e-01, -1.02389133e+00,  3.12690590e-01, -1.18962511e+00,
       -2.13619617e-01, -9.72730521e-02,  1.70157597e+00,  1.00821308e+00,
        2.62397438e+00,  8.49561033e-01,  8.32156251e-01, -6.25854098e-02,
       -1.45670593e+00, -8.21989129e-01, -1.42346477e+00, -8.38040625e-01,
       -2.62100249e-01, -3.62658145e-01,  4.61105820e-03, -1.07457979e+00,
       -2.99301532e-02, -1.00367644e+00, -3.29324169e-01, -1.26516002e-01,
        1.32217589e+00,  1.11289485e+00, -8.58812955e-01,  8.03170011e-02,
        1.13547128e+00,  1.22764461e+00, -2.48454568e-01,  1.23637031e+00,
       -5.75240086e-01,  5.57408541e-01,  1.33994342e+00, -5.92548130e-01,
        1.35663103e+00,  8.69188613e-01, -9.87145971e-01,  5.58620497e-02,
        2.20033596e-01,  9.71986980e-01,  7.11799245e-01, -3.97181408e-01,
        2.29496006e-01,  6.72811853e-01,  1.01315775e+00, -6.56228505e-01,
       -2.29132892e+00, -9.69830087e-01,  1.71093224e+00, -7.23270973e-02,
        1.41925693e-01,  1.45614928e+00, -1.45738549e+00,  4.03494999e-01,
        1.92410893e-01,  3.26396731e+00, -2.35957566e-01, -2.02338378e-01,
       -3.85839291e-01,  9.50305778e-01, -8.28738365e-01, -2.69456834e-01,
       -5.32050697e-01,  1.51659807e+00, -3.88603734e-01,  5.82101668e-01,
        5.45721347e-01,  1.07321109e+00, -1.28582004e-01, -3.80635148e-01,
        1.03056324e+00, -1.80279662e+00, -1.84424711e+00,  9.09764200e-01,
        1.49781558e-01, -1.20827802e-01, -4.73289690e-01, -1.39281152e-01,
       -8.06826146e-01, -2.03603366e+00,  5.23434842e-01,  2.49366993e+00,
       -8.66938770e-01,  1.06346836e+00,  1.15930035e+00,  1.04503970e+00,
       -4.22506947e-01, -5.99660302e-01,  7.34488089e-03,  4.16925494e-01,
        2.97353984e-01,  4.00872665e-01, -2.31973065e-01, -1.07988601e+00,
       -3.55659125e-01,  1.06265490e+00,  7.05808019e-01, -5.58960436e-01,
       -1.31146760e+00, -8.27104574e-01, -7.15387904e-01, -1.63636144e+00,
        4.83182271e-01, -1.00977556e+00, -1.88227681e+00,  4.42508207e-01,
       -2.05778546e+00,  1.82419355e+00,  9.51321821e-01,  1.39253978e+00,
        7.25230642e-01,  2.48381421e-02, -2.09091822e-01,  9.66867410e-01,
       -8.40751727e-01,  5.63168883e-01,  6.58755269e-01, -1.43716511e+00,
        1.38580483e+00, -3.21119127e-02, -5.34260329e-01, -2.70602132e-01])

In [75]:
quartiles = pd.qcut(data, 4, precision=2)
quartiles

[(-0.66, 0.018], (0.018, 0.72], (0.018, 0.72], (0.018, 0.72], (0.72, 3.65], ..., (-2.9299999999999997, -0.66], (0.72, 3.65], (-0.66, 0.018], (-0.66, 0.018], (-0.66, 0.018]]
Length: 1000
Categories (4, interval[float64, right]): [(-2.9299999999999997, -0.66] < (-0.66, 0.018] < (0.018, 0.72] < (0.72, 3.65]]

In [76]:
pd.value_counts(quartiles)

C:\Users\safye\AppData\Local\Temp\ipykernel_3096\3472704981.py:1: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  pd.value_counts(quartiles)

(-2.9299999999999997, -0.66]    250
(-0.66, 0.018]                  250
(0.018, 0.72]                   250
(0.72, 3.65]                    250
Name: count, dtype: int64

In [77]:
pd.qcut(data, [0, 0.1, 0.5, 0.9, 1.]).value_counts()

(-2.9219999999999997, -1.221]    100
(-1.221, 0.0184]                 400
(0.0184, 1.325]                  400
(1.325, 3.652]                   100
Name: count, dtype: int64

### Aykırı Değerleri Tespit Etme ve Filtreleme

In [78]:
data = pd.DataFrame(np.random.standard_normal((1000, 4)))

In [79]:
data.describe()

                 0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.016345    -0.049328     0.031839     0.024894
std       1.028388     1.015893     0.999367     1.027875
min      -2.936500    -3.037591    -2.816543    -2.896504
25%      -0.716230    -0.717175    -0.694126    -0.699952
50%       0.007792    -0.130145     0.048286     0.030012
75%       0.702443     0.647997     0.710210     0.747115
max       3.012485     3.558530     3.638145     3.314222

In [80]:
col = data[2]
col

0      1.278004
1      0.249404
2      0.400823
3     -0.554620
4      2.622967
         ...
995   -0.524097
996    0.654829
997    0.403847
998    0.000519
999    0.067245
Name: 2, Length: 1000, dtype: float64

In [81]:
col[col.abs() > 3]

532    3.010305
614    3.638145
Name: 2, dtype: float64

In [82]:
data[(data.abs() > 3).any(axis="columns")]

            0         1         2         3
32  -1.131623 -0.542845 -0.451754  3.314222
248  3.004830  0.667271  0.775940 -0.245633
359  0.277215  3.558530 -1.496773  1.193972
532  1.092723 -0.954295  3.010305 -0.680795
587 -0.074069  3.160350 -0.191241 -0.977213
614 -0.080579 -1.521470  3.638145 -0.944643
757 -0.115979 -3.037591 -1.257111 -0.303482
775  3.012485  0.643896  0.366615 -0.691331

In [83]:
data[data.abs() > 3] = np.sign(data)*3

In [84]:
data.describe()

                 0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.016362    -0.050009     0.031191     0.024580
std       1.028337     1.013454     0.997233     1.026916
min      -2.936500    -3.000000    -2.816543    -2.896504
25%      -0.716230    -0.717175    -0.694126    -0.699952
50%       0.007792    -0.130145     0.048286     0.030012
75%       0.702443     0.647997     0.710210     0.747115
max       3.000000     3.000000     3.000000     3.000000

In [85]:
np.sign(data).head()

     0    1    2    3
0  1.0  1.0  1.0 -1.0
1  1.0 -1.0  1.0  1.0
2  1.0 -1.0  1.0  1.0
3  1.0  1.0 -1.0  1.0
4 -1.0 -1.0  1.0 -1.0

### Gösterge/Kukla (Dummy) Değişkenleri Hesaplama

In [86]:
df = pd.DataFrame({"key": ["b", "b", "a", "c", "a", "b"], "data1": range(6)})

In [87]:
df

  key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   b      5

In [88]:
pd.get_dummies(df["key"])

       a      b      c
0  False   True  False
1  False   True  False
2   True  False  False
3  False  False   True
4   True  False  False
5  False   True  False

In [89]:
dummies = pd.get_dummies(df["key"], prefix="key")

In [90]:
df_with_dumy = df[["data1"]].join(dummies)

In [91]:
df_with_dumy

   data1  key_a  key_b  key_c
0      0  False   True  False
1      1  False   True  False
2      2   True  False  False
3      3  False  False   True
4      4   True  False  False
5      5  False   True  False

In [92]:
mnames = ["movie_id", "title", "genres"]

In [93]:
mnames

['movie_id', 'title', 'genres']

In [94]:
movies = pd.read_table("C:/Users/safye/Downloads/pydata-book-3rd-edition/pydata-book-3rd-edition/datasets/movielens/movies.dat", 
                       sep="::", header=None, names=mnames, engine="python")

In [95]:
movies[:10]

   movie_id                               title                        genres
0         1                    Toy Story (1995)   Animation|Children's|Comedy
1         2                      Jumanji (1995)  Adventure|Children's|Fantasy
2         3             Grumpier Old Men (1995)                Comedy|Romance
3         4            Waiting to Exhale (1995)                  Comedy|Drama
4         5  Father of the Bride Part II (1995)                        Comedy
5         6                         Heat (1995)         Action|Crime|Thriller
6         7                      Sabrina (1995)                Comedy|Romance
7         8                 Tom and Huck (1995)          Adventure|Children's
8         9                 Sudden Death (1995)                        Action
9        10                    GoldenEye (1995)     Action|Adventure|Thriller

In [96]:
dummies = movies["genres"].str.get_dummies("|")

In [97]:
dummies.iloc[:10, :6]

   Action  Adventure  Animation  Children's  Comedy  Crime
0       0          0          1           1       1      0
1       0          1          0           1       0      0
2       0          0          0           0       1      0
3       0          0          0           0       1      0
4       0          0          0           0       1      0
5       1          0          0           0       0      1
6       0          0          0           0       1      0
7       0          1          0           1       0      0
8       1          0          0           0       0      0
9       1          1          0           0       0      0

In [98]:
dummies.iloc[:10]

,Action,Adventure,Animation,Children's,Comedy,Crime,Documentary,Drama,Fantasy,Film-Noir,Horror,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western
0,0,0,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0
1,0,1,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0
2,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0
3,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
5,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0
6,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0
7,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
8,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
9,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0

In [99]:
movies_windic = movies.join(dummies.add_prefix("Genre_"))
movies_windic.iloc[0]

movie_id                                       1
title                           Toy Story (1995)
genres               Animation|Children's|Comedy
Genre_Action                                   0
Genre_Adventure                                0
Genre_Animation                                1
Genre_Children's                               1
Genre_Comedy                                   1
Genre_Crime                                    0
Genre_Documentary                              0
Genre_Drama                                    0
Genre_Fantasy                                  0
Genre_Film-Noir                                0
Genre_Horror                                   0
Genre_Musical                                  0
Genre_Mystery                                  0
Genre_Romance                                  0
Genre_Sci-Fi                                   0
Genre_Thriller                                 0
Genre_War                                      0
Genre_Western                                  0
Name: 0, dtype: object

In [100]:
movies_windic

,movie_id,title,genres,Genre_Action,Genre_Adventure,Genre_Animation,Genre_Children's,Genre_Comedy,Genre_Crime,Genre_Documentary,...,Genre_Fantasy,Genre_Film-Noir,Genre_Horror,Genre_Musical,Genre_Mystery,Genre_Romance,Genre_Sci-Fi,Genre_Thriller,Genre_War,Genre_Western
0,1,Toy Story (1995),Animation|Children's|Comedy,0,0,1,1,1,0,0,...,0,0,0,0,0,0,0,0,0,0
1,2,Jumanji (1995),Adventure|Children's|Fantasy,0,1,0,1,0,0,0,...,1,0,0,0,0,0,0,0,0,0
2,3,Grumpier Old Men (1995),Comedy|Romance,0,0,0,0,1,0,0,...,0,0,0,0,0,1,0,0,0,0
3,4,Waiting to Exhale (1995),Comedy|Drama,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
4,5,Father of the Bride Part II (1995),Comedy,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3878,3948,Meet the Parents (2000),Comedy,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
3879,3949,Requiem for a Dream (2000),Drama,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3880,3950,Tigerland (2000),Drama,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3881,3951,Two Family House (2000),Drama,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3882,3952,"Contender, The (2000)",Drama|Thriller,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0

In [101]:
np.random.seed(12345)
values = np.random.uniform(size=10)

In [102]:
values

array([0.92961609, 0.31637555, 0.18391881, 0.20456028, 0.56772503,
       0.5955447 , 0.96451452, 0.6531771 , 0.74890664, 0.65356987])

In [103]:
bins = [0, 0.2, 0.4, 0.6, 0.8, 1]

In [104]:
pd.get_dummies(pd.cut(values, bins))

   (0.0, 0.2]  (0.2, 0.4]  (0.4, 0.6]  (0.6, 0.8]  (0.8, 1.0]
0       False       False       False       False        True
1       False        True       False       False       False
2        True       False       False       False       False
3       False        True       False       False       False
4       False       False        True       False       False
5       False       False        True       False       False
6       False       False       False       False        True
7       False       False       False        True       False
8       False       False       False        True       False
9       False       False       False        True       False

In [105]:
s = pd.Series([1, 2, 3, None])

In [106]:
s

0    1.0
1    2.0
2    3.0
3    NaN
dtype: float64

In [107]:
s.dtype

dtype('float64')

In [108]:
s = pd.Series([1, 2, 3, None], dtype=pd.Int64Dtype())

In [109]:
s

0       1
1       2
2       3
3    <NA>
dtype: Int64

In [110]:
s.isna()

0    False
1    False
2    False
3     True
dtype: bool

In [111]:
s.dtype

Int64Dtype()

In [112]:
s[3]

In [113]:
s[3] is pd.NA

True

In [114]:
s = pd.Series([1, 2, 3, None], dtype="Int64")

In [115]:
s

0       1
1       2
2       3
3    <NA>
dtype: Int64

In [116]:
s = pd.Series(['one', 'two', None, 'three'], dtype=pd.StringDtype())

In [117]:
s

0      one
1      two
2     <NA>
3    three
dtype: string

In [118]:
df = pd.DataFrame({"A": [1, 2, None, 4],
                   "B": ["one", "two", "three", None],
                    "C": [False, None, False, True]})

In [119]:
df

     A      B      C
0  1.0    one  False
1  2.0    two   None
2  NaN  three  False
3  4.0   None   True

In [120]:
df["A"] = df["A"].astype("Int64")

In [121]:
df["B"] = df["B"].astype("string")

In [122]:
df["C"] = df["C"].astype("boolean")

In [123]:
df

      A      B      C
0     1    one  False
1     2    two   <NA>
2  <NA>  three  False
3     4   <NA>   True

## 7.4 Dize Manipülasyonu

### Python Yerleşik Dize Nesnesi Metotları

In [124]:
val = "a, b, guido"

In [125]:
val

'a, b, guido'

In [126]:
val.split(",")

['a', ' b', ' guido']

In [127]:
pieces = [x.strip() for x in val.split(",")]

In [128]:
pieces

['a', 'b', 'guido']

In [129]:
first, second, third = pieces
first + "::" + second + "::" + third

'a::b::guido'

In [130]:
"::".join(pieces)

'a::b::guido'

In [131]:
"guido" in val

True

In [132]:
val.index(",")

1

In [133]:
val.find(":")

-1

In [134]:
val.count(",")

2

In [135]:
val.replace(",", "::")

'a:: b:: guido'

In [136]:
val.replace(",", "")

'a b guido'

### Düzenli İfadeler (Regular Expressions)

In [137]:
import re

In [138]:
text = "foo bar\t baz \tqux"
text

'foo bar\t baz \tqux'

In [139]:
re.split(r"\s+", text)

['foo', 'bar', 'baz', 'qux']

In [140]:
regex = re.compile(r"\s+")
regex.split(text)

['foo', 'bar', 'baz', 'qux']

In [141]:
regex.findall(text)

[' ', '\t ', ' \t']

In [142]:
text = """Dave dave@google.com
Steve steve@gmail.com
Rob rob@gmail.com
Ryan ryan@yahoo.com"""

pattern = r"[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}"

In [143]:
# re.IGNORECASE regex'i büyük/küçük harfe duyarsız hale getirir
regex = re.compile(pattern, flags=re.IGNORECASE)

In [144]:
regex.findall(text)

['dave@google.com', 'steve@gmail.com', 'rob@gmail.com', 'ryan@yahoo.com']

In [145]:
m = regex.search(text)
m

In [146]:

text[m.start():m.end()]

'dave@google.com'

In [147]:
print(regex.match(text))

None

In [148]:
print(regex.sub("REDACTED", text))

Dave REDACTED
Steve REDACTED
Rob REDACTED
Ryan REDACTED

In [149]:
pattern = r"([A-Z0-9._%+-]+)@([A-Z0-9.-]+)\.([A-Z]{2,4})"
regex = re.compile(pattern, flags=re.IGNORECASE)

In [150]:
m = regex.match("wesm@bright.net")
m.groups()

('wesm', 'bright', 'net')

In [151]:
regex.findall(text)

[('dave', 'google', 'com'),
 ('steve', 'gmail', 'com'),
 ('rob', 'gmail', 'com'),
 ('ryan', 'yahoo', 'com')]

In [152]:
print(regex.sub(r"Username: \1, Domain: \2, Suffix: \3", text))

Dave Username: dave, Domain: google, Suffix: com
Steve Username: steve, Domain: gmail, Suffix: com
Rob Username: rob, Domain: gmail, Suffix: com
Ryan Username: ryan, Domain: yahoo, Suffix: com

### Pandas İçinde Dizgi Fonksiyonları (String Functions in pandas)

In [153]:
data = {"Dave": "dave@google.com", "Steve": "steve@gmail.com", "Rob": "rob@gmail.com", "Wes": np.nan}
data

{'Dave': 'dave@google.com',
 'Steve': 'steve@gmail.com',
 'Rob': 'rob@gmail.com',
 'Wes': nan}

In [155]:
data = pd.Series(data)
data

Dave     dave@google.com
Steve    steve@gmail.com
Rob        rob@gmail.com
Wes                  NaN
dtype: object

In [156]:
data.isna()

Dave     False
Steve    False
Rob      False
Wes       True
dtype: bool

In [157]:
data.str.contains("gmail")

Dave     False
Steve     True
Rob       True
Wes        NaN
dtype: object

In [158]:
data_as_string_ext = data.astype('string')
data_as_string_ext.str.contains("gmail")

Dave     False
Steve     True
Rob       True
Wes       <NA>
dtype: boolean

In [160]:
pattern = r"([A-Z0-9._%+-]+)@([A-Z0-9.-]+)\.([A-Z]{2,4})"
data.str.findall(pattern, flags=re.IGNORECASE)

Dave     [(dave, google, com)]
Steve    [(steve, gmail, com)]
Rob        [(rob, gmail, com)]
Wes                        NaN
dtype: object

In [162]:
matches = data.str.findall(pattern, flags=re.IGNORECASE).str[0]
matches

Dave     (dave, google, com)
Steve    (steve, gmail, com)
Rob        (rob, gmail, com)
Wes                      NaN
dtype: object

In [163]:
matches.str.get(1)

Dave     google
Steve     gmail
Rob       gmail
Wes         NaN
dtype: object

In [164]:
data.str[:5]

Dave     dave@
Steve    steve
Rob      rob@g
Wes        NaN
dtype: object

In [165]:
data.str.extract(pattern, flags=re.IGNORECASE)

           0       1    2
Dave    dave  google  com
Steve  steve   gmail  com
Rob      rob   gmail  com
Wes      NaN     NaN  NaN

### 7.5 Kategorik Veri (Categorical Data)

### Arka Plan ve Motivasyon (Background and Motivation)

In [166]:
values = pd.Series(['apple', 'orange', 'apple', 'apple'] * 2)
values

0     apple
1    orange
2     apple
3     apple
4     apple
5    orange
6     apple
7     apple
dtype: object

In [167]:
pd.unique(values)

array(['apple', 'orange'], dtype=object)

In [168]:
pd.value_counts(values)

C:\Users\safye\AppData\Local\Temp\ipykernel_3096\3297668723.py:1: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  pd.value_counts(values)

apple     6
orange    2
Name: count, dtype: int64

In [169]:
values = pd.Series([0, 1, 0, 0] * 2)
dim = pd.Series(['apple', 'orange'])

In [170]:
values

0    0
1    1
2    0
3    0
4    0
5    1
6    0
7    0
dtype: int64

In [171]:
dim

0     apple
1    orange
dtype: object

In [172]:
dim.take(values)

0     apple
1    orange
0     apple
0     apple
0     apple
1    orange
0     apple
0     apple
dtype: object

### Pandas'ta Kategorik Uzantı Tipi (Categorical Extension Type in pandas)

In [175]:
fruits = ['apple', 'orange', 'apple', 'apple'] * 2
N = len(fruits)
N

8

In [177]:
rng = np.random.default_rng(seed=12345)

In [178]:
df = pd.DataFrame({'fruit': fruits,
                   'basket_id': np.arange(N),
                   'count': rng.integers(3, 15, size=N),
                   'weight': rng.uniform(0, 4, size=N)},
                   columns=['basket_id', 'fruit', 'count', 'weight'])

In [179]:
df

   basket_id   fruit  count    weight
0          0   apple     11  1.564438
1          1  orange      5  1.331256
2          2   apple     12  2.393235
3          3   apple      6  0.746937
4          4   apple      5  2.691024
5          5  orange     12  3.767211
6          6   apple     10  0.992983
7          7   apple     11  3.795525

In [184]:
fruit_cat = df['fruit'].astype('category')
fruit_cat

0     apple
1    orange
2     apple
3     apple
4     apple
5    orange
6     apple
7     apple
Name: fruit, dtype: category
Categories (2, object): ['apple', 'orange']

In [186]:
c = fruit_cat.array
type(c)

pandas.core.arrays.categorical.Categorical

In [187]:
c.categories

Index(['apple', 'orange'], dtype='object')

In [188]:
c.codes

array([0, 1, 0, 0, 0, 1, 0, 0], dtype=int8)

In [189]:
dict(enumerate(c.categories))

{0: 'apple', 1: 'orange'}

In [190]:
df['fruit'] = df['fruit'].astype('category')
df["fruit"]

0     apple
1    orange
2     apple
3     apple
4     apple
5    orange
6     apple
7     apple
Name: fruit, dtype: category
Categories (2, object): ['apple', 'orange']

In [192]:
my_categories = pd.Categorical(['foo', 'bar', 'baz', 'foo', 'bar'])
my_categories

['foo', 'bar', 'baz', 'foo', 'bar']
Categories (3, object): ['bar', 'baz', 'foo']

In [194]:
categories = ['foo', 'bar', 'baz']
codes = [0, 1, 2, 0, 0, 1]

In [195]:
my_cats_2 = pd.Categorical.from_codes(codes, categories)
my_cats_2

['foo', 'bar', 'baz', 'foo', 'foo', 'bar']
Categories (3, object): ['foo', 'bar', 'baz']

In [197]:
ordered_cat = pd.Categorical.from_codes(codes, categories, ordered=True)
ordered_cat

['foo', 'bar', 'baz', 'foo', 'foo', 'bar']
Categories (3, object): ['foo' < 'bar' < 'baz']

In [198]:
my_cats_2.as_ordered()

['foo', 'bar', 'baz', 'foo', 'foo', 'bar']
Categories (3, object): ['foo' < 'bar' < 'baz']